insert into usuarios_usuario (nome, email, senha) values ('admin', 'admin@admin.com', 'ac9689e2272427085e35b9d3e3e8bed88cb3434828b43b86fc0596cad4c6e270');

INSERT INTO livro_livros (titulo, autor, genero) VALUES ('O Mundo Mágico de Harry Potter','David Colbert','Aventura'),
	('Almas Antigas','Tom Shroder','Não Ficção'),
	('Um Dia "Daqueles"','BTG','Sci-Fi'),
	('A Tenda Vermelha','Anita Diamant','Aventura'),
	('A Tenda Vermelha','Anita Diamant','Romace'),
	('Querida Mamãe','BTG','Não Ficção'),
	('A Economia do Ócio','Domenico de Masi','Não Ficção'),
	('Minha Terra e Meu Povo','XIV Dalai Lama (Tenzin Gyatso)','Não Ficção'),
	('Salvando meu filho','Richard Galli','Sci-Fi'),
	('Ontem, Eu chorei','Iyanla Vanzant','Aventura'),
	('Histórias para Aquecer o Coração 2','Jack Canfield','Fantasia'),
	('Aprendendo a gostar de si mesmo','Louise Hay','Ficção'),
	('Mensagens dos Mestres','Brian Weiss','Sci-Fi'),
	('Espiritualidade: um Caminho de Transformação','Leonardo Boff','Suspense'),
	('Meditações Celestinas','SALLE MERRILL REDFIELD','Mistério'),
	('A força da vida','James Van Praagh','Ficção'),
	('Da Esperança à Utopia','Dom Paulo Evaristo Arns','Sci-Fi'),
	('As bençãos do meu avô','Rachel Naomi Remen','Aventura'),
	('Espiritualidade','Leonardo Boff','Não Ficção'),
	('Como Proteger Seus Filhos','Gavin De Becker','Aventura'),
	('Histórias para Aquecer o Coração','Jack Canfield','Não Ficção'),
	('O Desenho Infantil','Florence de Mèredieu','Ficção'),
	('Megabiodiversidade Brasil','Ibsen de Gusmão Câmara','Romace'),
	('Comunhão com Deus','Neale Donald Walsch','Aventura'),
	('Transcarioca, todos os passos de um sonho','Pedro da Cunha e Menezes','Ficção'),
	('Palavras de Sabedoria','XIV Dalai Lama (Tenzin Gyatso)','Ficção'),
	('Mantenha o Seu Cérebro Vivo','Lawrence C. Katz','Romace'),
	('Mantenha o Seu Cérebro Vivo','Lawrence C. Katz','Fantasia'),
	('O Ócio Criativo','Domenico de Masi','Não Ficção'),
	('Para viver um amor de verdade','Daphne Rose','Suspense'),
	('A Arte de Viver','Epicteto','Sci-Fi'),
	('Uma Amizade com Deus','Neale Donald Walsch','Não Ficção'),
	('Um dia minha alma se abriu por inteiro','Iyanla Vanzant','Não Ficção'),
	('Esperando o amor chegar','Iyanla Vanzant','Romace'),
	('O Outro Lado da Vida','Sylvia Browne','Sci-Fi'),
	('Em busca do perdão','James Van Praagh','Não Ficção'),
	('Eu era uma ótima mãe até ter filhos','Trisha Ashworth e Amy Nobile','Mistério'),
	('Tempo de Transcedência','Leonardo Boff','Não Ficção'),
	('O Convite','Oriah Mountain Dreamer','Romace'),
	('Por que os Homens Amam as Mulheres Poderosas?','Sherry Argov','Fantasia'),
	('O Caminho','Sextante','Fantasia'),
	('A Vida no Outro Lado','Sylvia Browne','Sci-Fi'),
	('Uma ética para o novo milênio','XIV Dalai Lama (Tenzin Gyatso)','Aventura'),
	('A arte de viver','Epicteto','Fantasia'),
	('Descobrindo a alegria de viver','Salle Merrill Redfield','Aventura'),
	('O Caminho','SHIRLEY MCLAINE','Não Ficção'),
	('Sua Santidade, o Dalai-Lama','XIV Dalai Lama (Tenzin Gyatso)','Aventura'),
	('Meditação para a Saúde do Corpo e da Mente','Louise L. Hay','Mistério'),
	('Os Caminhos do Coração','Richard Carlson','Mistério'),
	('Mantenha o seu cérebro vivo','Lawrence C. Katrz','Suspense'),
	('Mantenha seu cérebro vivo','Laurence C. Katz','Romace'),
	('Como Fazer um Excelente Currículo','Yana Parker','Romace'),
	('A Divina Sabedoria dos Mestres','Brian Weiss','Fantasia'),
	('Patch Adams: O Amor é Contagioso','Patch Adams','Romace'),
	('Enquanto o amor não vem','Iyanla Vanzant','Não Ficção'),
	('Enquanto o amor não vem','Iyanla Vanzant','Suspense'),
	('A Roda da Vida','Elisabeth Kübler-Ross','Romace'),
	('Em Busca da Espiritualidade','James Van Praagh','Suspense'),
	('Pequenos Milagres II','Yitta Halberstam','Ficção'),
	('A Oração de São Francisco','Leonardo Boff','Não Ficção'),
	('Velejando com a vida','Richard Bode','Romace'),
	('Uma ética para o novo milênio','XIV Dalai Lama (Tenzin Gyatso)','Sci-Fi'),
	('A arte da meditação','Daniel Goleman','Fantasia'),
	('Meditações para gestantes','Fadynha','Romace'),
	('Meditações para a manhã e a noite','Louise L. Hay','Não Ficção'),
	('O Brasil e os Holandeses','Sextante','Fantasia'),
	('Lições sobre amar e viver','Morrie Schwartz','Ficção'),
	('A Essencial Arte de Parar','Dr. David Kundtz','Suspense'),
	('Patch Adams','Patch Adams','Mistério'),
	('LIÇÕES SOBRE AMAR E VIVER','SEXTANTE','Não Ficção'),
	('A Última Grande Lição','Mitch Albom','Romace'),
	('A Última Grande Lição','Mitch Albom','Fantasia'),
	('Meditando com Brian Weiss','Brian Weiss','Ficção'),
	('Sua Santidade, o Dalai-Lama','XIV Dalai Lama (Tenzin Gyatso)','Sci-Fi'),
	('Pequenos Milagres','Yitta Halberstam e Judith Leventhal','Suspense'),
	('Espartilhos e Sutiãs: uma História da Sedução','Beatrice Fontanel','Fantasia'),
	('Os Mensageiros','Sextante','Sci-Fi'),
	('Conversando com os Espíritos','James Van Praagh','Suspense'),
	('Meditando com Brian Weiss','Brian Weiss','Aventura'),
	('Conversando com os Espíritos','James Van Praagh','Aventura'),
	('Pequenos Milagres','Yitta Halberstam e Judith Leventhal','Suspense'),
	('A estrela de Lancaster','Jean Plaidy','Mistério'),
	('100 Vezes Ique no Estadão','Vários','Não Ficção'),
	('Só o Amor É Real','Brian Weiss','Mistério'),
	('Como conseguir um emprego e descobrir sua profissão ideal','Richard N. Bolles','Fantasia'),
	('Faça sua luz brilhar','Neale Donald Walsch','Suspense'),
	('Pense Melhor, Viva Melhor','Sextante','Ficção'),
	('Many Lives, Many Masters','Brian Weiss','Suspense'),
	('Ética da Vida','Leonardo Boff','Sci-Fi'),
	('História de Um Grande Amor','Julia Quinn','Mistério'),
	('História de Um Grande Amor','Julia Quinn','Aventura'),
	('De Repente Uma Noite de Paixão','Lisa Kleypas','Mistério'),
	('De Sangue e Ossos','Nora Roberts','Fantasia'),
	('Palácio da traição','Jason Matthews','Ficção'),
	('Não Há Segunda Chance','Harlan Coben','Fantasia'),
	('O Que Acontece Em Londres','Julia Quinn','Sci-Fi'),
	('O Que Acontece Em Londres','Julia Quinn','Ficção'),
	('Meu jeito certo de fazer tudo errado','Klara Castanho','Romace'),
	('Não fale com estranhos','Harlan Coben','Suspense'),
	('A Honra das Terras Altas','Hannah Howell','Mistério'),
	('A prisioneira do tempo','Kate Morton','Suspense'),
	('Dama da Névoa','Laura Sebastian','Mistério'),
	('Uma Promessa e Nada Mais','Mary Balogh','Mistério'),
	('A Gaiola de Ouro','Camilla Läckberg','Romace'),
	('Notre-Dame','Ken Follett','Mistério'),
	('O Guia Definitivo do Mochileiro das Galáxias',' Douglas Adams','Não Ficção'),
	('A Cruz de Fogo','Diana Gabaldon','Mistério'),
	('O Duque Que Eu Conquistei','Scarlett Peckham','Ficção'),
	('O Guia Definitivo Do Mochileiro Das Galáxias + Marcadores Imantados','Douglas Adams','Suspense'),
	('Dez coisas que eu amo em você','Julia Quinn','Ficção'),
	('A Adorável Loja de Chocolates de Paris','Jenny Colgan','Mistério'),
	('Sinfonia dos Animais','Dan Brown','Fantasia'),
	('Uma Noiva Rebelde','Julia Quinn','Não Ficção'),
	('O Duque e Eu','Julia Quinn','Suspense'),
	('Um Beijo e Nada Mais','Mary Balogh','Romace'),
	('Um Beijo e Nada Mais','Mary Balogh','Romace'),
	('A Irmã do Sol','Lucinda Riley','Fantasia'),
	('O Crepúsculo e a Aurora','Ken Follett','Não Ficção'),
	('Box Trilogia O Século: Queda de gigantes - Inverno do mundo - Eternidade por um fio','Ken Follet','Sci-Fi'),
	('Quatro Amores Na Escócia','Julia Quinn','Suspense'),
	('Cartada final','John Grisham','Ficção'),
	('Custe O Que Custar','Harlan Coben','Mistério'),
	('A Prisioneira do Tempo','Kate Morton','Sci-Fi'),
	('Seis Anos Depois','Harlan Coben','Suspense'),
	('Desaparecido para Sempre','Harlan Coben','Mistério'),
	('Custe O Que Custar','Harlan Coben','Romace'),
	('Na Corda Bamba','Kiley Reid','Aventura'),
	('Escrito Com o Sangue do Meu Coração','Diana Gabaldon','Sci-Fi'),
	('Cartada final','John Grisham','Não Ficção'),
	('O Dossiê Pelicano','John Grisham','Não Ficção'),
	('Questão de Classe','Christina Dalcher','Romace'),
	('A Origem','Dan Brown','Mistério'),
	('O Melhor de Mim','Nicholas Sparks','Mistério'),
	('Pelo o amor de Cassandra','Lisa Kleypas','Sci-Fi'),
	('O Retorno','Nicholas Sparks','Mistério'),
	('O Sal das Lágrimas','Ruta Sepetys','Sci-Fi'),
	('No Meu Sonho Te Amei','Abbi Glines','Sci-Fi'),
	('Um Marido de Faz de Conta','Julia Quinn','Sci-Fi'),
	('Um Marido de faz de Conta','Julia Quinn','Romace'),
	('Um Estranho Irresistível','Lisa Kleypas','Mistério'),
	('A Caça','M.A. Bennett','Suspense'),
	('Até o Fim','Harlan Coben','Mistério'),
	('Cinzas Na Neve','Ruta Sepetys','Sci-Fi'),
	('O Destino das Terras Altas','Hannah Howell','Aventura'),
	('O Homem Inocente','John Grisham','Romace'),
	('A Carta Secreta','Lucinda Riley','Não Ficção'),
	('Tudo Que a Gente Sempre Quis','Emily Giffin','Não Ficção'),
	('Artemis','Andy Weir','Sci-Fi'),
	('Esse Duque é Meu','Eloisa James','Romace'),
	('Esperança','Lesley Pearse','Não Ficção'),
	('Um Casamento Americano','Tayari Jones','Romace'),
	('Tripla Espionagem','Ken Follett','Fantasia'),
	('Tripla espionagem','Ken Follett','Não Ficção'),
	('O sol também é uma estrela','Nicola Yoon','Sci-Fi'),
	('A Dama Mais Desejada','Julia Quinn','Aventura'),
	('Já Disse Que Te Amo?','Estelle Maskame','Não Ficção'),
	('A Pequena Livraria dos Sonhos','Jenny Colgan','Não Ficção'),
	('Desencontros à Beira-Mar','Jill Mansell','Fantasia'),
	('A Casa dos Novos Começos','Lucy Diamond','Suspense'),
	('Não conte a ninguém','Harlan Coben','Não Ficção'),
	('Quando ela se foi','Harlan Coben','Fantasia'),
	('Marionete','Daniel Cole','Fantasia'),
	('Ano Um','Nora Roberts','Sci-Fi'),
	('Box Os Bridgertons: Série completa com os 9 títulos','Julia Quinn','Suspense'),
	('Alta Tensão','Harlan Coben','Mistério'),
	('Confie em Mim','Harlan Coben','Fantasia'),
	('Mulher-Gato: Ladra de Almas','Sarah J. Maas','Não Ficção'),
	('Uma Loucura e Nada Mais','Mary Balogh','Fantasia'),
	('O Pretendente','Mary Balogh','Aventura'),
	('Ecos do Futuro','Diana Gabaldon','Sci-Fi'),
	('Ecos do Futuro','Diana Gabaldon','Não Ficção'),
	('A Firma','John Grisham','Fantasia'),
	('Um Cavalheiro a Bordo','Julia Quinn','Romace'),
	('Um Cavalheiro a Bordo','Julia Quinn','Suspense'),
	('Um Amor para Recordar','Nicholas Sparks','Aventura'),
	('Vox','Christina Dalcher','Aventura'),
	('A Chama de Ember','Colleen Houck','Não Ficção'),
	('Confissões de uma garota linda, popular e (secretamente) infeliz','Thalita Rebouças','Romace'),
	('Cilada','Harlan Coben','Aventura'),
	('Uma Paixão e Nada Mais','Mary Balogh','Romace'),
	('A Revolta de Atlas','Ayn Rand','Não Ficção'),
	('A Padaria dos Finais Felizes','Jenny Colgan','Sci-Fi'),
	('A Garota do Penhasco','Lucinda Riley','Suspense'),
	('O Fim dos Tempos','Thomas M. Campion','Sci-Fi'),
	('A Dama Mais Apaixonada','Julia Quinn','Suspense'),
	('A Garota do Penhasco','Lucinda Riley','Aventura'),
	('Onde Mora o Amor','Jill Mansell','Romace'),
	('A Intérprete','Annette Hess','Ficção'),
	('Tempo de Regresso','Kristin Hannah','Aventura'),
	('Uma Fortuna Perigosa','Ken Follett','Mistério'),
	('Quebra de Confiança','Harlan Coben','Suspense'),
	('A Dama mais Apaixonada','Julia Quinn','Fantasia'),
	('O Primeiro Imortal','Rodrigo Alvarez','Aventura'),
	('O Café da Praia','Lucy Diamond','Fantasia'),
	('O Café da Praia','Lucy Diamond','Mistério'),
	('Apenas Um Olhar','Harlan Coben','Romace'),
	('Tempo de graça, tempo de dor','Frances de Pontes Peebles','Não Ficção'),
	('Acerto de Contas','John Grisham','Fantasia'),
	('A Sala das Borboletas','Lucinda Riley','Ficção'),
	('O Golpe','Christopher Reich','Não Ficção'),
	('Uma Herdeira Apaixonada','Lisa Kleypas','Sci-Fi'),
	('Uma Herdeira Apaixonada','Lisa Kleypas','Mistério'),
	('Acerto De Contas','John Grisham','Sci-Fi'),
	('A Última Música','Nicholas Sparks','Mistério'),
	('Se eu Ficar','Gayle Forman','Aventura'),
	('A mulher na janela','A.J. Finn','Suspense'),
	('Sonhos em Flor','Estelle Laure','Romace'),
	('Meia Guerra','Joe Abercrombie','Não Ficção'),
	('Império das Tormentas','Jon Skovron','Fantasia'),
	('A Coroa da Vingança','Colleen Houck','Aventura'),
	('Mais Lindo Que a Lua','Julia Quinn','Suspense'),
	('As Crônicas de Marte','George R. R. Martin','Suspense'),
	('Sem Fôlego','Abbi Glines','Mistério'),
	('A Libélula No Âmbar','Diana Gabaldon','Fantasia'),
	('Mudbound: Lágrimas Sobre o Mississippi','Hillary Jordan','Romace'),
	('Batman: Criaturas da Noite','Marie Lu','Sci-Fi'),
	('A Viajante do Tempo','Diana Gabaldon','Fantasia'),
	('Batman: Criaturas da Noite','Marie Lu','Suspense'),
	('Um Sedutor Sem Coração','Lisa Kleypas','Mistério'),
	('Um Homem de Sorte','Nicholas Sparks','Ficção'),
	('O Livro e a Espada','Antoine Rouaud','Ficção'),
	('Os Quase Completos','Felippe Barbosa','Aventura'),
	('A Mulher Na Janela','A.J. Finn','Ficção'),
	('Operação Red Sparrow','Jason Matthews','Aventura'),
	('Contagem Regressiva','Ken Follett','Não Ficção'),
	('Estrelas da Sorte','Nora Roberts','Não Ficção'),
	('Uma Proposta e Nada Mais','Mary Balogh','Ficção'),
	('O Resgate No Mar','Diana Gabaldon','Romace'),
	('Volta Para Casa','Harlan Coben','Sci-Fi'),
	('Nada Escapa a Lady Whistledown','Julia Quinn','Aventura'),
	('A Luz Que Perdemos','Jill Santopolo','Mistério'),
	('O Segredo de Helena','Lucinda Riley','Não Ficção'),
	('Os Portais da Casa dos Mortos','Steven Erikson','Fantasia'),
	('Mais Forte Que o Sol','Julia Quinn','Ficção'),
	('Dentes de Dragão','Michael Crichton','Ficção'),
	('Um Sopro de Neve e Cinzas','Diana Gabaldon','Romace'),
	('A Duquesa Feia','Eloisa James','Aventura'),
	('Uma Noiva Para Winterborne','Lisa Kleypas','Romace'),
	('Baía dos Suspiros','Nora Roberts','Fantasia'),
	('O Sonho do Tigre','Colleen Houck','Ficção'),
	('A Casa das Orquídeas','Lucinda Riley','Aventura'),
	('Uma Dama Fora dos Padrões','Julia Quinn','Aventura'),
	('Almas Gêmeas','Nicholas Sparks','Mistério'),
	('O Jardim Esquecido','Kate Morton','Não Ficção'),
	('Eu Perdi o Rumo','Gayle Forman','Fantasia'),
	('Sem Escolha','Abbi Glines','Mistério'),
	('Um Acordo e Nada Mais','Mary Balogh','Sci-Fi'),
	('A Torre do Amor','Eloisa James','Fantasia'),
	('O Buraco da Agulha','Ken Follett','Sci-Fi'),
	('Princesa das Cinzas','Laura Sebastian','Fantasia');
INSERT INTO livro_livros (titulo, autor, genero) VALUES ('A Grande Solidão','Kristin Hannah','Fantasia'),
	('Vox','Christina Dalcher','Ficção'),
	('A Cruz de Fogo','Diana Gabaldon','Aventura'),
	('A Irmã da Lua','Lucinda Riley','Fantasia'),
	('Justiça a Qualquer Preço','John Grisham','Mistério'),
	('Ilha de Vidro','Nora Roberts','Suspense'),
	('Um Acordo Pecaminoso','Lisa Kleypas','Romace'),
	('Os Tambores do Outono','Diana Gabaldon','Fantasia'),
	('Uma dama fora dos padrões','Julia Quinn','Ficção'),
	('O Sonho do Tigre','Colleen Houck','Suspense'),
	('A mulher na janela','A.J. Finn','Não Ficção'),
	('Uma Carta de Amor','Nicholas Sparks','Fantasia'),
	('Ao Seu Encontro','Abbi Glines','Romace'),
	('Ninfeias Negras','Michel Bussi','Aventura'),
	('Escândalos Na Primavera','Lisa Kleypas','Sci-Fi'),
	('Meio Mundo','Joe Abercrombie','Ficção'),
	('O Caminho Para Casa','Kristin Hannah','Mistério'),
	('Uma carta de amor','Nicholas Sparks','Aventura'),
	('O Resgate no Mar','Diana Gabaldon','Romace'),
	('Simplesmente o Paraíso','Julia Quinn','Suspense'),
	('Uma Noite Como Esta','Julia Quinn','Mistério'),
	('A Soma de Todos os Beijos','Julia Quinn','Mistério'),
	('Os Mistérios de Sir Richard','Julia Quinn','Fantasia'),
	('A Cabana','William P. Young','Fantasia'),
	('Box Quarteto Smythe-Smith','Julia Quinn','Romace'),
	('Meu Jeito Certo de Fazer Tudo Errado','Klara Castanho','Aventura'),
	('A Cruz de Fogo','Diana Gabaldon','Ficção'),
	('A Promessa','Harlan Coben','Mistério'),
	('A Rainha das Trevas','Anne Bishop','Não Ficção'),
	('Diário de Uma Paixão','Nicholas Sparks','Aventura'),
	('O Sol Também é Uma Estrela','Nicola Yoon','Não Ficção'),
	('Jardins da Lua','Steven Erikson','Fantasia'),
	('À Margem das Sombras','Brent Weeks','Romace'),
	('A Chave de Rebecca','Ken Follett','Romace'),
	('Ligeiramente Perigosos','Mary Balogh','Ficção'),
	('Irmãos de Sangue','Nora Roberts','Romace'),
	('A Cruz de Fogo','Diana Gabaldon','Fantasia'),
	('Tudo e Todas As Coisas','Nicola Yoon','Ficção'),
	('Dois a Dois','Nicholas Sparks','Mistério'),
	('Boneco de Pano','Daniel Cole','Sci-Fi'),
	('Amanhã Eu Paro!','Gilles Legardinier','Romace'),
	('As Tumbas de Atuan','Ursula K. Le Guin','Ficção'),
	('O Voo da Vespa','Ken Follett','Fantasia'),
	('A Árvore dos Anjos','Lucinda Riley','Fantasia'),
	('Mestre das Chamas','Joe Hill','Suspense'),
	('O Duelo dos Imortais','Colleen Houck','Mistério'),
	('A Grande Ilusão','Harlan Coben','Fantasia'),
	('Nossa Música','Dani Atkins','Aventura'),
	('A Casa do Lago','Kate Morton','Aventura'),
	('Uma Noite Inesquecível','Lisa Kleypas','Aventura'),
	('Quando a Bela Domou a Fera','Eloisa James','Aventura'),
	('Um Menino em Um Milhão','Monica Wood','Aventura'),
	('Confissões de Um Garoto Tímido, Nerd e (Ligeiramente) Apaixonado','Thalita Rebouças','Não Ficção'),
	('Coluna de Fogo','Ken Follett','Ficção'),
	('O Último Adeus','Abbi Glines','Fantasia'),
	('Onze Leis a Cumprir Na Hora de Seduzir','Sarah MacLean','Fantasia'),
	('Volúpia de Veludo','Loretta Chase','Aventura'),
	('Meus Dias Com Você','Clare Swatman','Ficção'),
	('A Maldição de Hollow','Nora Roberts','Mistério'),
	('Mulher-Maravilha: Sementes da Guerra','Leigh Bardugo','Romace'),
	('Fortaleza Impossível','Jason Rekulak','Romace'),
	('Amor Sem Medidas','Sophie Jackson','Romace'),
	('Pegando Fogo','Abbi Glines','Aventura'),
	('A Pérola Que Rompeu a Concha','Nadia Hashimi','Ficção'),
	('Origem','Dan Brown','Sci-Fi'),
	('A Pedra Pagã','Nora Roberts','Fantasia'),
	('Um Beijo à Meia-Noite','Eloisa James','Mistério'),
	('Como Agarrar Uma Herdeira','Julia Quinn','Suspense'),
	('Como Se Casar Com Um Marquês','Julia Quinn','Ficção'),
	('Romance Entre Rendas','Loretta Chase','Ficção'),
	('As Coisas Que Fazemos Por Amor','Kristin Hannah','Não Ficção'),
	('Querido John','Nicholas Sparks','Mistério'),
	('Lady Whistledown Contra-Ataca','Julia Quinn','Romace'),
	('Entre Irmãs','Frances de Pontes Peebles','Romace'),
	('Depois Daquela Montanha','Charles Martin','Ficção'),
	('A Irmã da Pérola','Lucinda Riley','Não Ficção'),
	('A Pérola Que Partiu a Concha','Nadia Hashimi','Mistério'),
	('Tipos Incomuns (Algumas Histórias)',' Tom Hanks','Não Ficção'),
	('Como agarrar uma herdeira','Julia Quinn','Não Ficção'),
	('Escola 8 - Austrália, aqui vou eu!','James Patterson','Ficção'),
	('Amanhã Eu Paro!','Gilles Legardinier','Ficção'),
	('O Casamento','Nicholas Sparks','Romace'),
	('O Guardião','Nicholas Sparks','Mistério'),
	('Um Beijo Inesquecível','Julia Quinn','Ficção'),
	('A Caminho do Altar','Julia Quinn','Não Ficção'),
	('Mais Uma Chance','Abbi Glines','Ficção'),
	('O Que Há de Estranho em Mim','Gayle Forman','Não Ficção'),
	('Enquanto Bela Dormia','Elizabeth Blackwell','Mistério'),
	('Mais uma Chance','Abbi Glines','Fantasia'),
	('Eternamente Você','Sophie Jackson','Não Ficção'),
	('O Leão Ferido','Mia Sheridan','Suspense'),
	('Volta Para Mim','Mila Gray','Romace'),
	('A Escolha','Nicholas Sparks','Mistério'),
	('A Garota Sem Passado','Michael Kardos','Aventura'),
	('A Travessia','William P. Young','Suspense'),
	('Nove Regras a Ignorar Antes de Se Apaixonar','Sarah MacLean','Mistério'),
	('Era Uma Vez No Outono','Lisa Kleypas','Mistério'),
	('Os Tambores de Outono','Diana Gabaldon','Mistério'),
	('Uma História Incomum Sobre Livros e Magia','Lisa Papademetriou','Ficção'),
	('Caminho das Sombras','Brent Weeks','Fantasia'),
	('Um Novo Amanhã','Nora Roberts','Não Ficção'),
	('Pecados No Inverno','Lisa Kleypas','Sci-Fi'),
	('Profundo','Robin York','Mistério'),
	('Intenso','Robin York','Sci-Fi'),
	('O Quarto Dia','Sarah Lotz','Sci-Fi'),
	('Trama','Michael Jensen','Romace'),
	('No Seu Olhar','Nicholas Sparks','Ficção'),
	('A História de Nós Dois','Dani Atkins','Mistério'),
	('Paixão Libertadora','Sophie Jackson','Suspense'),
	('Ligeiramente Seduzidos','Mary Balogh','Mistério'),
	('Aprendiz','Raymond E. Feist','Sci-Fi'),
	('Mestre','Raymond E. Feist','Não Ficção'),
	('As Trevas de Sethanon','Raymond E. Feist','Não Ficção'),
	('Espinho de Prata','Raymond E. Feist','Aventura'),
	('O Mensageiro','Lois Lowry','Mistério'),
	('O Guia Definitivo do Mochileiro das Galáxias',' Douglas Adams','Mistério'),
	('Sedução da Seda','Loretta Chase','Aventura'),
	('Confissões de Uma Garota Excluída, Mal - Amada e (Um Pouco) Dramática','Thalita Rebouças','Romace'),
	('Não Fale Com Estranhos','Harlan Coben','Fantasia'),
	('Os Tambores do Outono','Diana Gabaldon','Ficção'),
	('A Garota Italiana','Lucinda Riley','Ficção'),
	('Meio Rei','Joe Abercrombie','Fantasia'),
	('Três Coisas Sobre Você','Julie Buxbaum','Aventura'),
	('Eu Sem Você','Kelly Rimmer','Romace'),
	('O Principe de Westeros e Outras Historias','George R. R. Martin','Sci-Fi'),
	('Noite Sobre as Águas','Ken Follett','Ficção'),
	('Para Sempre Minha','Abbi Glines','Ficção'),
	('Pecados no Inverno','Lisa Kleypas','Sci-Fi'),
	('O Eterno Namorado','Nora Roberts','Sci-Fi'),
	('Longa e Sombria Hora do Chá da Alma',' Douglas Adams','Ficção'),
	('Veneno','Mia Sheridan','Romace'),
	(' A Viajante do Tempo','Diana Gabaldon','Suspense'),
	('Apenas Um Garoto','Bill Konigsberg','Não Ficção'),
	('As Cores Da Vida','Kristin Hannah','Fantasia'),
	('A Senhora do Império','Raymond E. Feist','Sci-Fi'),
	('Essa Luz Tão Brilhante','Estelle Laure','Ficção'),
	('As Sete Irmãs','Lucinda Riley','Romace'),
	('A Irmã da Tempestade','Lucinda Riley','Aventura'),
	('Quando o Amor Bater à Sua Porta','Samanta Holtz','Romace'),
	('A Irmã da Sombra','Lucinda Riley','Suspense'),
	('O Coração da Esfinge','Colleen Houck','Fantasia'),
	('O Feiticeiro de Terramar','Ursula K. Le Guin','Fantasia'),
	('O Medo Mais Profundo','Harlan Coben','Romace'),
	('Um Porto Seguro','Nicholas Sparks','Sci-Fi'),
	('O Guardião','Nicholas Sparks','Aventura'),
	('Dez Formas De Fazer Um Coração Se Derreter','Sarah MacLean','Não Ficção'),
	('À Sua Espera','Abbi Glines','Aventura'),
	('O Código Da Vinci','Dan Brown','Não Ficção'),
	('A Sombra do Passado','Sylvain Reynard','Não Ficção'),
	('Ligeiramente Pecaminosos','Mary Balogh','Aventura'),
	('Depois Daquela Montanha','Charles Martin','Mistério'),
	('O Primeiro Dia do Resto da Nossa Vida','Kate Eberlen','Ficção'),
	('Kiro e Emily','Abbi Glines','Não Ficção'),
	('As Cordas Mágicas','Mitch Albom','Aventura'),
	('E Viveram Felizes Para Sempre','Julia Quinn','Ficção'),
	('O Homem de São Petersburgo','Ken Follett','Suspense'),
	('O Par Perfeito','Nora Roberts','Não Ficção'),
	('Escândalo de Cetim','Loretta Chase','Fantasia'),
	('A Cidade dos Espelhos','Justin Cronin','Fantasia'),
	('À Primeira Vista','Nicholas Sparks','Sci-Fi'),
	('O Casamento','Nicholas Sparks','Sci-Fi'),
	('Dois a Dois','Nicholas Sparks','Suspense'),
	('Escola 7 - O Melhor Amigo do Cão','James Patterson','Ficção'),
	('Nove Regras a Ignorar Antes de se Apaixonar','Sarah MacLean','Romace'),
	('Mago, Aprendiz','Raymond E. Feist','Romace'),
	('Mago, Mestre','Raymond E. Feist','Fantasia'),
	('Mago, Espinho de Prata','Raymond E. Feist','Romace'),
	('Mago, As Trevas de Sethanon','Raymond E. Feist','Sci-Fi'),
	('O Duelo dos Reis','Joe Abercrombie','Fantasia'),
	('Para Sir Phillip, Com Amor','Julia Quinn','Romace'),
	('O Conde Enfeitiçado','Julia Quinn','Aventura'),
	('República de Ladrões','Scott Lynch','Aventura'),
	('A Música do Silêncio','Patrick Rothfuss','Sci-Fi'),
	('O Príncipe das Sombras','Sylvain Reynard','Ficção'),
	('Paixão ao Entardecer','Lisa Kleypas','Não Ficção'),
	('Segredos de Um Pecador','Madeline Hunter','Ficção'),
	('Ligeiramente Maliciosos','Mary Balogh','Não Ficção'),
	('O Príncipe dos Canalhas','Loretta Chase','Fantasia'),
	('Simples Perfeição','Abbi Glines','Sci-Fi'),
	('Morte Invisível','Lene Kaaberbøl','Suspense'),
	('Bruxa da Noite','Nora Roberts','Suspense'),
	('Amaldiçoado','Joe Hill','Fantasia'),
	('A Linguagem das Flores','Vanessa Diffenbaugh','Sci-Fi'),
	('A Toda Prova','Harlan Coben','Sci-Fi'),
	('A Rainha Normanda','Patricia Bracewell','Não Ficção'),
	('Perdas e Danos','Diane Chamberlain','Não Ficção'),
	('Tensão','Gail McHugh','Ficção'),
	('O Voo da Libélula','Michel Bussi','Não Ficção'),
	('Uma Longa Jornada','Nicholas Sparks','Suspense'),
	('A Transformação de Raven','Sylvain Reynard','Sci-Fi'),
	('A Primeira Chance','Abbi Glines','Não Ficção'),
	('Agência de Investigações Holísticas Dirk Gently',' Douglas Adams','Romace'),
	('O Sangue do Cordeiro','Sam Cabot','Romace'),
	('Predestinadas','Jessica Spotswood','Não Ficção'),
	('O Milagre','Nicholas Sparks','Fantasia'),
	('Que Falta Você Me Faz','Harlan Coben','Sci-Fi'),
	('Uma Curva No Tempo','Dani Atkins','Mistério'),
	('Rush Sem Limites','Abbi Glines','Romace'),
	('Segredos de Uma Noite de Verão','Lisa Kleypas','Ficção'),
	('As Espiãs do Dia D','Ken Follett','Não Ficção'),
	('O Que Eu Quero Pra Mim','Lycia Barros','Não Ficção'),
	('Eu Estive Aqui','Gayle Forman','Aventura'),
	('Memórias de Uma Gueixa','Arthur Golden','Romace'),
	('Três Semanas Com Meu Irmão','Nicholas Sparks','Aventura'),
	('As Regras da Sedução','Madeline Hunter','Suspense'),
	('Lições do Desejo','Madeline Hunter','Ficção'),
	('Pulsação','Gail McHugh','Sci-Fi'),
	('Feitiço da Sombra','Nora Roberts','Mistério'),
	('O Despertar do Príncipe','Colleen Houck','Ficção'),
	('Antes de Partir Desta Pra Uma Melhor','Jonathan Tropper','Romace'),
	('Peter Pan Tem Que Morrer','John Verdon','Não Ficção'),
	('Ligeiramente Escandalosos','Mary Balogh','Não Ficção'),
	('A Voz do Arqueiro','Mia Sheridan','Mistério'),
	('O Manuscrito','Chris Pavone','Romace'),
	('Zoo','James Patterson','Sci-Fi'),
	('Perdido em Marte','Andy Weir','Suspense'),
	('Desejo Proibido','Sophie Jackson','Ficção'),
	('A Garota Inglesa','Daniel Silva','Mistério'),
	('A Irmandade Perdida','Anne Fortier','Não Ficção'),
	('Detalhe Final','Harlan Coben','Mistério'),
	('Confissões de Inverno','Brendan Kiely','Suspense'),
	('Noites de Tormenta','Nicholas Sparks','Fantasia'),
	('O Rouxinol','Kristin Hannah','Aventura'),
	('O Coração do Leão','Mia Sheridan','Sci-Fi'),
	('A Irmã da Tempestade','Lucinda Riley','Ficção'),
	('O Último dos Canalhas','Loretta Chase','Suspense'),
	('Mundo Sem Fim','Ken Follett','Suspense'),
	('Magia do Sangue','Nora Roberts','Aventura'),
	('Eva','William P. Young','Fantasia'),
	('Quarteto de Noivas','Nora Roberts','Aventura'),
	('Uma Longa Jornada','Nicholas Sparks','Mistério'),
	('Fortaleza Digital','Dan Brown','Ficção'),
	('O guia definitivo do mochileiro das galáxias',' Douglas Adams','Mistério'),
	('Paixão ao Entardecer','Lisa Kleypas','Aventura'),
	('Os Mercadores da Noite','Ivan Sant''Anna','Aventura'),
	('Uma Curva Na Estrada','Nicholas Sparks','Não Ficção'),
	('Tentação ao Pôr do Sol','Lisa Kleypas','Mistério'),
	('Antes da Forca','Joe Abercrombie','Fantasia'),
	('A Redenção de Gabriel','Sylvain Reynard','Aventura'),
	('Um Perfeito Cavalheiro','Julia Quinn','Suspense'),
	('Jogos do Prazer','Madeline Hunter','Fantasia'),
	('Mar de Rosas','Nora Roberts','Não Ficção'),
	('Enfeitiçadas','Jessica Spotswood','Fantasia'),
	('As Mentiras de Locke Lamora','Scott Lynch','Fantasia'),
	('Tentação Sem Limites','Abbi Glines','Romace'),
	('9º Julgamento','James Patterson','Não Ficção'),
	('Terra Sem Lei','John Sandford','Mistério'),
	('Amigas Para Sempre','Kristin Hannah','Fantasia'),
	('Segredos e Mentiras','Diane Chamberlain','Romace'),
	('Manhã de Núpcias','Lisa Kleypas','Não Ficção');
INSERT INTO livro_livros (titulo, autor, genero) VALUES ('Os Segredos de Colin Bridgerton','Julia Quinn','Suspense'),
	('Amaldiçoadas','Jessica Spotswood','Fantasia'),
	('Roleta Russa','Jason Matthews','Ficção'),
	('Os Assassinos do Cartão-Postal','Liza Marklund','Ficção'),
	('Querida Sue','Jessica Brockmole','Ficção'),
	('Bem-Casados','Nora Roberts','Fantasia'),
	('Estranha Perfeição','Abbi Glines','Sci-Fi'),
	('A Promessa do Tigre','Colleen Houck','Romace'),
	('Os Três','Sarah Lotz','Romace'),
	('Escravas de Coragem','Kathleen Grissom','Ficção'),
	('O Salmão da Dúvida',' Douglas Adams','Ficção'),
	('Julieta','Anne Fortier','Não Ficção'),
	('Mares de Sangue','Scott Lynch','Aventura'),
	('Seis Anos Depois','Harlan Coben','Não Ficção'),
	('O Sobrevivente','Gregg Hurwitz','Fantasia'),
	('O Resgate','Nicholas Sparks','Não Ficção'),
	('Reconstruindo Amelia','Kimberly McCreight','Mistério'),
	('Nosferatu','Joe Hill','Sci-Fi'),
	('A Bandeja','Lycia Barros','Suspense'),
	('Eternidade Por Um Fio','Ken Follett','Sci-Fi'),
	('Private - Londres','James Patterson','Suspense'),
	('O Doador de Memórias','Lois Lowry','Romace'),
	('Amor Sem Limites','Abbi Glines','Ficção'),
	('Mar da tranquilidade','Katja Millay','Ficção'),
	('O Sexto Homem','David Baldacci','Ficção'),
	('Primavera Eterna','Paula Abreu','Sci-Fi'),
	('Ligeiramente Casados','Mary Balogh','Romace'),
	('O Desertor','Daniel Silva','Não Ficção'),
	('Perdido em Marte','Andy Weir','Aventura'),
	('Sete Dias Sem Fim','Jonathan Tropper','Mistério'),
	('O Melhor de Mim','Nicholas Sparks','Aventura'),
	('O Primeiro Telefonema do Céu','Mitch Albom','Ficção'),
	('Corra, Alex Cross','James Patterson','Mistério'),
	('Um Passo em Falso','Harlan Coben','Suspense'),
	('A Escolhida','Lois Lowry','Romace'),
	('Um lugar chamado liberdade','Ken Follett','Não Ficção'),
	('Inferno','Dan Brown','Não Ficção'),
	('A Promessa do Tigre','Colleen Houck','Ficção'),
	('Manhã de Núpcias','Lisa Kleypas','Ficção'),
	('Como Salvar Um Vampiro Apaixonado','Beth Fantaskey','Não Ficção'),
	('Escola: Os Piores Anos da Minha Vida','James Patterson','Ficção'),
	('O Destino do Tigre','Colleen Houck','Ficção'),
	('Os Doze','Justin Cronin','Fantasia'),
	('O Julgamento de Gabriel','Sylvain Reynard','Romace'),
	('Lua de Mel','James Patterson','Não Ficção'),
	('Um Certo Verão','David Baldacci','Mistério'),
	('O Inferno de Gabriel','Sylvain Reynard','Mistério'),
	('Inferno','Dan Brown','Mistério'),
	('Profecia','S. J. Parris','Sci-Fi'),
	('É Melhor Não Saber','Chevy Stevens','Fantasia'),
	('O Preço da Vitória','Harlan Coben','Aventura'),
	('Poder Absoluto','David Baldacci','Suspense'),
	('Juntos Para Sempre','Walcyr Carrasco','Não Ficção'),
	('Noite de Tempestade','John Sandford','Mistério'),
	('Fique Comigo','Harlan Coben','Mistério'),
	('Retrato de Uma Espiã','Daniel Silva','Fantasia'),
	('Desejo à Meia-Noite','Lisa Kleypas','Sci-Fi'),
	('O Duque e Eu','Julia Quinn','Sci-Fi'),
	('As Regras da Sedução','Madeline Hunter','Ficção'),
	('Você é o Próximo','Gregg Hurwitz','Romace'),
	('Quando Você Voltar','Kristin Hannah','Fantasia'),
	('O Maior Amor do Mundo','Seré Prince Halverson','Fantasia'),
	('Armadilhas da Mente','Augusto Cury','Aventura'),
	('Os Impostores','Chris Pavone','Suspense'),
	('Sete Dias Sem Fim','Jonathan Tropper','Suspense'),
	('O Guardião do Tempo','Mitch Albom','Aventura'),
	('8ª Confissão','James Patterson','Mistério'),
	('Sedução ao Amanhecer','Lisa Kleypas','Aventura'),
	('Uma Questão de Segundos','Harlan Coben','Romace'),
	('O Menino da Mala','Lene Kaaberbøl','Não Ficção'),
	('O Poder da Espada','Joe Abercrombie','Não Ficção'),
	('Private - Suspeito Nº 1','James Patterson','Ficção'),
	('O Visconde Que Me Amava','Julia Quinn','Mistério'),
	('Não Brinque Com Fogo','John Verdon','Suspense'),
	('Uma Longa Jornada','Nicholas Sparks','Ficção'),
	('Lições do Desejo','Madeline Hunter','Suspense'),
	('Livrai-nos do Mal','David Baldacci','Mistério'),
	('Escola 2: O Rebelde Está de Volta!','James Patterson','Não Ficção'),
	('Dançando Sobre Cacos de Vidro','Ka Hancock','Aventura'),
	('Anjo Caído','Daniel Silva','Suspense'),
	('Pela Luz dos Olhos Seus','Janine Boissard','Sci-Fi'),
	('Onde Mora A Coragem','Stanley Gordon West','Não Ficção'),
	('Sessão de Terapia','Jaqueline Vargas','Ficção'),
	('Marcoré','Antônio Olavo Pereira','Aventura'),
	('Álbum de Casamento','Nora Roberts','Romace'),
	('Lua Vermelha','Benjamin Percy','Ficção'),
	('Paixão Sem Limites','Abbi Glines','Aventura'),
	('Feliz Natal, Alex Cross','James Patterson,','Não Ficção'),
	('O Inocente','Harlan Coben','Suspense'),
	('A Maldição do Tigre','Colleen Houck','Aventura'),
	('O Destino do Tigre','Colleen Houck','Suspense'),
	('Desejo à Meia-Noite','Lisa Kleypas','Romace'),
	('Sedução ao Amanhecer','Lisa Kleypas','Romace'),
	('O Símbolo Perdido','Dan Brown','Ficção'),
	('A Sombra da Lua','John Sandford','Não Ficção'),
	('Tudo pode mudar','Jonathan Tropper','Mistério'),
	('O Resgate do Tigre','Colleen Houck','Romace'),
	('Jogada Mortal','Harlan Coben','Romace'),
	('Dias de Chuva e Tempestade','Nancy Pickard','Ficção'),
	('Nunca Diga Adeus','Doug Magee','Não Ficção'),
	('O Melhor de Mim','Nicholas Sparks','Sci-Fi'),
	('Fogo Cruzado','James Patterson','Aventura'),
	('6º Alvo','James Patterson','Fantasia'),
	('Private - Agência Internacional de Investigações','James Patterson','Fantasia'),
	('Guerreiros da Esperança','Andrea Hirata','Mistério'),
	('A Viagem do Tigre','Colleen Houck','Sci-Fi'),
	('Você Está Sendo Vigiado','Gregg Hurwitz','Aventura'),
	('Refúgio','Harlan Coben','Não Ficção'),
	('Private - Missão Jogos Olímpicos','James Patterson','Não Ficção'),
	('Feche Bem os Olhos','John Verdon','Romace'),
	('A Cabana','William P. Young','Romace'),
	('Traição em Família','David Baldacci','Mistério'),
	('Inverno do Mundo','Ken Follett','Não Ficção'),
	('O Caso Rembrandt','Daniel Silva','Fantasia'),
	('Os Mistérios da Coroa','Nancy Bilyeau','Mistério'),
	('O caminho para casa','Kristin Hannah','Fantasia'),
	('Sem Deixar Rastros','Harlan Coben','Não Ficção'),
	('A Travessia','William P. Young','Aventura'),
	('Corajosos','Randy Alcorn','Mistério'),
	('Ameaça Mortal','James Patterson','Aventura'),
	('7° Céu','James Patterson','Romace'),
	('À Primeira Vista','Nicholas Sparks','Aventura'),
	('O Código Da Vinci','Dan Brown','Fantasia'),
	('O Casamento','Nicholas Sparks','Mistério'),
	('A Maldição do Tigre','Colleen Houck','Aventura'),
	('O Resgate do Tigre','Colleen Houck','Aventura'),
	('A Traição','Christopher Reich','Não Ficção'),
	('Heresia','S. J. Parris','Suspense'),
	('Lago dos Sonhos','Kim Edwards','Aventura'),
	('Ladrões de Elite','Ally Carter','Romace'),
	('Quando Ela Se Foi','Harlan Coben','Sci-Fi'),
	('Identidade Roubada','Chevy Stevens','Sci-Fi'),
	('Eu Sei O Que Você Está Pensando','John Verdon','Sci-Fi'),
	('Como Se Livrar de Um Vampiro Apaixonado','Beth Fantaskey','Ficção'),
	('A Vida em Tons de Cinza','Ruta Sepetys','Aventura'),
	('Água para Elefantes','Sara Gruen','Romace'),
	('A Linguagem das Flores','Vanessa Diffenbaugh','Não Ficção'),
	('4 de Julho','James Patterson','Fantasia'),
	('O Dia da Caça','James Patterson','Suspense'),
	('Alta Tensão','Harlan Coben','Não Ficção'),
	('A Maldição do Tigre','Colleen Houck','Suspense'),
	('O Diário de Suzana Para Nicolas','James Patterson','Fantasia'),
	('Quebra de Confiança','Harlan Coben','Fantasia'),
	('Toda a Verdade','David Baldacci','Romace'),
	('O Temor do Sábio','Patrick Rothfuss','Romace'),
	('Eu, Alex Cross','James Patterson','Sci-Fi'),
	('5º Cavaleiro','James Patterson','Aventura'),
	('Box A maldição do tigre','Colleen Houck','Sci-Fi'),
	('A Passagem','Justin Cronin','Suspense'),
	('Cilada','Harlan Coben','Aventura'),
	('Queda de Gigantes','Ken Follett','Suspense'),
	('Julieta','Anne Fortier','Fantasia'),
	('A Revolta de Atlas','Ayn Rand','Suspense'),
	('O Futuro Da Humanidade','Augusto Cury','Sci-Fi'),
	('A Vida, o Universo e Tudo Mais',' Douglas Adams','Mistério'),
	('A Farsa','Christopher Reich','Aventura'),
	('Desaparecido Para Sempre','Harlan Coben','Fantasia'),
	('O Símbolo Perdido','Dan Brown','Romace'),
	('O Guardião de Memórias','Kim Edwards','Mistério'),
	('E Tem Outra Coisa...','Eoin Colfer','Aventura'),
	('O Nome do Vento','Patrick Rothfuss','Fantasia'),
	('Fortaleza Digital','Dan Brown','Ficção'),
	('A Cabana','William P. Young','Mistério'),
	('A Estrada da Noite','Joe Hill','Mistério'),
	('A Conspiração Franciscana','John Sack','Sci-Fi'),
	('Ponto De Impacto','Dan Brown','Romace'),
	('Anjos e Demônios','Dan Brown','Sci-Fi'),
	('Corte de Chamas Prateadas','Sarah J. Maas','Romace'),
	('Beijos em Nova York','Catherine Rider','Aventura'),
	('O cuidadoso despir do amor','Corey Ann Haydu','Ficção'),
	('League of Legends: Reinos de Runeterra','Riot Games','Sci-Fi'),
	('Como sair com homens quando você odeia homens','Blythe Roberson','Mistério'),
	('Verity','Colleen Hoover','Aventura'),
	('O Rei Perverso','Holly Black','Ficção'),
	('O Rei Perverso','Holly Black','Romace'),
	('Box Trono de Vidro (Acompanha Brindes)','Sarah J mass','Mistério'),
	('Chain of Gold','Cassandra Clare','Aventura'),
	('A onda','Todd Strasser','Suspense'),
	('Cidade dos Ossos','Cassandra Clare','Suspense'),
	('Querido Ex','Juan Jullian','Romace'),
	('Talvez Agora','Colleen Hoover','Mistério'),
	('Guia de alimentação e cuidado de um buraco negro de estimação','Michelle Cuevas','Romace'),
	('Fada-na-fila-de-espera','Sophie Kinsella','Sci-Fi'),
	('Box Corte de Espinhos e Rosas 4 Volumes (Acompanha Brindes)','Sarah J. Maas','Não Ficção'),
	('Casa de Terra e Sangue','Sarah J. Maas','Sci-Fi'),
	('Artemis Fowl: O menino prodígio do crime','Eoin Colfer','Fantasia'),
	('Reino de Cinzas','Sarah J. Maas','Aventura'),
	('Meninas Selvagens','Rory Power','Não Ficção'),
	('Princesa Mecânica','Cassandra Clare','Suspense'),
	('Box As Peças Infernais 3 volumes','Cassandra Clare','Fantasia'),
	('Meninas selvagens','Rory Power','Romace'),
	('Você tem a vida inteira','Lucas Rocha','Ficção'),
	('O Guia da Donzela para Anáguas e Pirataria','Mackenzi Lee','Romace'),
	('Casa de Terra e Sangue','Sarah J. Maas','Fantasia'),
	('Corrente de Ouro','Cassandra Clare','Não Ficção'),
	('Êxtase','Lauren Kate','Mistério'),
	('A Rainha do Nada','Holly Black','Suspense'),
	('Casa De Terra E Sangue (vol. 1 Cidade Da Lua Crescente)','Sarah J. Maas','Romace'),
	('O ódio que você semeia','Angie Thomas','Fantasia'),
	('Se não fosse você','Colleen Hoover','Suspense'),
	('Corrente de Ouro','Cassandra Clare','Não Ficção'),
	('Corte de Espinhos e Rosas','Sarah J. Maas','Fantasia'),
	('Corte de Névoa e Fúria','Sarah J. Maas','Aventura'),
	('Corte de Asas e Ruína','Sarah J. Maas','Suspense'),
	('Corte de Gelo e Estrelas','Sarah J. Maas','Sci-Fi'),
	('Para Sempre Caídos','Cassandra Clare','Mistério'),
	('O Mundo Perdido','Cassandra Clare','Sci-Fi'),
	('Talvez Agora','Colleen Hoover','Suspense'),
	('A mão que te alimenta','A. J. Rich','Ficção'),
	('Rainha do Ar e da Escuridão','Cassandra Clare','Mistério'),
	('O destino dos deuses','Matthew J. Kirby','Sci-Fi'),
	('Crianças do Éden','Joey Graceffa','Fantasia'),
	('Cinderela Pop','Paula Pimenta','Ficção'),
	('Através do sangue, através do fogo','Cassandra Clare','Aventura'),
	('Reino de Cinzas','Sarah J. Maas','Não Ficção'),
	('Nunca Jamais','Colleen Hoover','Ficção'),
	('A Fada Mamãe e Eu','Sophie Kinsella','Fantasia'),
	('BTS: A biografia não oficial dos ícones do K-Pop','Adrain Besley','Suspense'),
	('A Torre de Ouro','Holly Black','Aventura'),
	('36 perguntas que mudaram o que sinto por você','Vicki Grant','Suspense'),
	('À Beira da Eternidade','Melissa E. Hurst','Fantasia'),
	('36 perguntas que mudaram o que sinto por você','Vicki Grant','Não Ficção'),
	('Impostores','Scott Westerfeld','Aventura'),
	('Especial','Ryan O''Connell','Aventura'),
	('Quando Não Há Palavras','Julie Buxbaum','Fantasia'),
	('Confidências de Uma Ex-Popular','Ray Tavares','Fantasia'),
	('Refugiados','Alan Gratz','Fantasia'),
	('Refugiados','Alan Gratz','Sci-Fi'),
	('Você Sabe Onde Me Encontrar','Rachel Cohn','Fantasia'),
	('Na Hora da Virada','Angie Thomas','Sci-Fi'),
	('Todas as Suas (Im)Perfeições','Colleen Hoover','Fantasia'),
	('Todas as Suas (Im)Perfeições','Colleen Hoover','Sci-Fi'),
	('Mortos Não Contam Segredos','Karen M. McManus','Romace'),
	('Mortos Não Contam Segredos','Karen M. McManus','Sci-Fi'),
	('Fantasmas do Mercado das Sombras','Cassandra Clare','Aventura'),
	('Cidade das Almas Perdidas e Cidade do Fogo Celestial','Cassandra Clare','Fantasia'),
	('As Três Partes de Grace','Robin Benway','Fantasia'),
	('World of Warcraft - Antes da Tempestade','Christie Golden','Ficção'),
	('Império de Tempestades - Tomo Único','Sarah J. Maas','Mistério'),
	('As Quatro Rainhas Mortas','Astrid Scholte','Suspense'),
	('As Quatro Rainhas Mortas','Astrid Scholte','Romace'),
	('Algum Dia','David Levithan','Romace'),
	('Use A Moda A Seu Favor','Carla Lemos','Ficção'),
	('Mais classificados e nem tanto','Marina Colasanti','Mistério'),
	('Os Pergaminhos Vermelhos da Magia','Wesley Chu','Ficção'),
	('O Amor Não é Obvio',' Elayne Baeta','Mistério'),
	('Algum Dia','David Levithan','Suspense'),
	('Trono de Vidro','Sarah J. Maas','Fantasia'),
	('Confidências de uma ex-popular','Ray Tavares','Não Ficção'),
	('Cidade dos Anjos Caídos','Cassandra Clare','Suspense');
INSERT INTO livro_livros (titulo, autor, genero) VALUES ('Cidade das Almas Perdidas','Cassandra Clare','Sci-Fi'),
	('Cidade dos Ossos','Cassandra Clare','Fantasia'),
	('Cidade de Vidro','Cassandra Clare','Aventura'),
	('Cidade das Cinzas','Cassandra Clare','Mistério'),
	('Cidade do Fogo Celestial','Cassandra Clare','Mistério'),
	('Cidade das Almas Perdidas','Cassandra Clare','Sci-Fi'),
	('Harry Potter - O Livro das Varinhas','Monique Peterson','Sci-Fi'),
	('É Assim Que Acaba','Colleen Hoover','Suspense'),
	('Um de Nós Está Mentindo','Karen M. McManus','Aventura'),
	('A Garota Que Bebeu a Lua','Kelly Barnhill','Suspense'),
	('Renascer','Anna Carey','Não Ficção'),
	('A Tentação','L. J. Smith','Mistério'),
	('A Colisão dos Mundos','Ned Vizzini','Romace'),
	('A Falta Que Me Faz','Meg Cabot','Não Ficção'),
	('A Gaiola Dourada','Vic James','Fantasia'),
	('Cidade dos Anjos Caídos','Cassandra Clare','Sci-Fi'),
	('Frio Congelante','Sarah Mlynowski','Ficção'),
	('Heresia','S. J. Parris','Mistério'),
	('Sorte Grande','Jennifer E. Smith','Não Ficção'),
	('O Tipo Certo de Garota Errada','A.C. Meyer','Suspense'),
	('Liberdade','Andrea Portes','Suspense'),
	('As Cartas Que Escrevemos','Brittainy Cherry','Sci-Fi'),
	('13 Segundos','Bel Rodrigues','Mistério'),
	('Heroínas','Pam Gonçalves','Mistério'),
	('Merlin. O Espelho do Destino - Volume 4','T. A. Barron','Mistério'),
	('Doce Reencontro','A.C. Meyer','Sci-Fi'),
	('O Diário de uma Pestinha','Virginy L. Sam','Mistério'),
	('Tarde Demais','Colleen Hoover','Ficção'),
	('Você Tem a Vida Inteira','Lucas Rocha','Sci-Fi'),
	('Filho do Amanhecer (Son of the Dawn)','Cassandra Clare','Suspense'),
	('A Construção de Noah Shaw','Michelle Hodkin','Mistério'),
	('Longas Sombras','Cassandra Clare','Fantasia'),
	('O Guia do Cavalheiro Para o Vício e a Virtude','Mackenzi Lee','Romace'),
	('Bruxa Akata','Nnedi Okorafor','Ficção'),
	('Além das cores','Camila Moreira','Fantasia'),
	('Todas as Coisas Extraordinárias','Cassandra Clare','Não Ficção'),
	('O Mistério do Relógio na Parede','John Bellairs','Ficção'),
	('50 Brasileiras Incríveis Para Conhecer Antes de Crescer','Débora Thomé','Suspense'),
	('A Poeta X','Elizabeth Acevedo','Romace'),
	('O Príncipe Cruel','Holly Black','Aventura'),
	('Arte & Alma','Brittainy Cherry','Suspense'),
	('Aprendendo sobre perdas','Cassandra Clare','Mistério'),
	('Diário de Uma Ansiosa ou Como Parei de Me Sabotar','Beth Evans','Mistério'),
	('Sob a Capa Vermelha','Mariana Vitória','Suspense'),
	('As Mil Partes do Meu Coração','Colleen Hoover','Ficção'),
	('Um amor mais profundo','Cassandra Clare','Suspense'),
	('Choque de Cultura - 79 Filmes Pra Assistir Enquanto Dirige','Caito Mainier','Suspense'),
	('O que é um homem? (Vol. 1 Que legal pensar!)','Cécile Robelin','Suspense'),
	('Corte de Gelo e Estrelas','Sarah J. Maas','Ficção'),
	('O ódio que você semeia','Angie Thomas','Aventura'),
	('Os Perversos','Cassandra Clare','Sci-Fi'),
	('Preso em Battle Royale: Batalha nos Campos Fatais','Devin Hunter','Suspense'),
	('Bom Ano','Pam Gonçalves','Aventura'),
	('A Terra que Perdi','Cassandra Clare','Ficção'),
	('13 Segundos','Bel Rodrigues','Fantasia'),
	('13 Segundos','Bel Rodrigues','Suspense'),
	('Corte de Névoa e Fúria','Sarah J. Maas','Fantasia'),
	('Um de Nós Está Mentindo','Karen M. McManus','Sci-Fi'),
	('Cidade das Cinzas','Cassandra Clare','Romace'),
	('Diários do Vampiro','L. J. Smith','Mistério'),
	('A Festa dos Sonhos','Sarah Mlynowski','Sci-Fi'),
	('The Walking Dead','Jay Bonansinga','Ficção'),
	('Nunca Jamais','Colleen Hoover','Sci-Fi'),
	('A Inquisição','Taran Matharu','Não Ficção'),
	('Império de Tempestades - Tomo 1','Sarah J. Maas','Suspense'),
	('Cadu e Mari','A.C. Meyer','Suspense'),
	('Contos da Academia dos Caçadores de Sombras','Cassandra Clare','Aventura'),
	('Esqueça o Amanhã','Pintip Dunn','Sci-Fi'),
	('Império de Tempestades - Tomo 2','Sarah J. Maas','Fantasia'),
	('A Árvore no Quintal','Jeff Gottesfeld','Fantasia'),
	('Victoria e o Patife','Meg Cabot','Não Ficção'),
	('Anatomia de Um Excluído','Andrea Portes','Não Ficção'),
	('Missão Cupido','Kieran Scott','Aventura'),
	('Aliança','Mark Frost','Não Ficção'),
	('Missão','Aaron Becker','Não Ficção'),
	('Bruxa de Sangue','Cate Tiernan','Não Ficção'),
	('O canto mais escuro da floresta','Holly Black','Mistério'),
	('À Primeira Vista','David Levithan','Romace'),
	('Anna Liza e o Consultório Feliz','Eoin Colfer','Aventura'),
	('O Vespeiro','Kenneth Oppel','Suspense'),
	('Time Humanos','Justine Larbalestier','Sci-Fi'),
	('Londres é Nossa!','Sarra Manning','Suspense'),
	('Os Quatro Cavaleiros','Veronica Rossi','Romace'),
	('O Ódio Que Você Semeia','Angie Thomas','Aventura'),
	('Graça e Maldição','Laure Eve','Não Ficção'),
	('O Encantador de Corvos',' Jacob Grey','Romace'),
	('ABC do Amor','A.C. Meyer','Romace'),
	('Belinda & Em','Cammie McGovern','Aventura'),
	('O Livro das Princesas','Paula Pimenta','Mistério'),
	('O Melhor Guia de K-pop Real Oficial','Hugo Francioni','Fantasia'),
	('Os 12 Signos de Valentina','Ray Tavares','Suspense'),
	('Confesse','Colleen Hoover','Ficção'),
	('A Terra das Sombras','Meg Cabot','Aventura'),
	('O Túmulo de Khan','Matthew J. Kirby','Sci-Fi'),
	('Starcraft: Evolução','Timothy Zahn','Fantasia'),
	('O Portal','Laura Ruby','Não Ficção'),
	('Treze','FML Pepper','Mistério'),
	('O Garoto Está de Volta','Meg Cabot','Não Ficção'),
	('O Problema do Para Sempre','Jennifer L. Armentrout','Fantasia'),
	('Lock & Mori','Heather W. Petty','Aventura'),
	('Uma História de Verão','Pam Gonçalves','Aventura'),
	('Senhor das Sombras','Cassandra Clare','Mistério'),
	('Harry Potter: As Artes das Trevas','Jody Revenson','Suspense'),
	('A Caça ao Snark','Lewis Carroll','Fantasia'),
	('Um Dia Embaraçado','Sarah Mlynowski','Sci-Fi'),
	('Nicola e o Visconde','Meg Cabot','Ficção'),
	('As Delícias da Fofoca','Cecily von Ziegesar','Sci-Fi'),
	('Perfeitos','Scott Westerfeld','Sci-Fi'),
	('A Court of Wings and Ruin','Sarah J. Maas','Ficção'),
	('Corte de Asas e Ruína','Sarah J. Maas','Mistério'),
	('Desastre No Casamento Real','Meg Cabot','Mistério'),
	('Menina Veneno','Carina Rissi','Sci-Fi'),
	('Minha Irmã Rosa','Justine Larbalestier','Suspense'),
	('Otolina e A Raposa Roxa','Chris Riddell','Fantasia'),
	('Bela Gratidão','Corey Ann Haydu','Suspense'),
	('Criaturas e Criadores','Raphael Draccon','Ficção'),
	('Ruína','Amy Tintera','Não Ficção'),
	('Olá, Adeus e Tudo Mais','Jennifer E. Smith','Mistério'),
	('Uma Sombra Ardente e Brilhante','Jessica Cluess','Fantasia'),
	('Corte de Asas e Ruína','Sarah J. Maas','Romace'),
	('Wink Poppy Midnight','April Genevieve Tucholke','Não Ficção'),
	('Batalha na Costa Oceânica','Mark Cheverton','Romace'),
	('50 Brasileiras Incríveis Para Conhecer Antes de Crescer','Débora Thomé','Suspense'),
	('Assassin''s Creed Origins. Juramento do Deserto','Oliver Bowden','Não Ficção'),
	('O Mago de Batalha','Taran Matharu','Suspense'),
	('Escrito a Fogo','Marcus Sakey','Aventura'),
	('Sem Filtro','Lily Collins','Suspense'),
	('O Regicida',' Virginia Boecker','Fantasia'),
	('A Máscara de Prata (The Silver Mask)','Cassandra Clare','Sci-Fi'),
	('Cidade de Selvagens','Lee Kelly','Mistério'),
	('Lock e Mori','Heather W. Petty','Romace'),
	('TREZE','FML Pepper','Mistério'),
	('A Caçada','L. J. Smith','Suspense'),
	('Corte de Espinhos e Rosas','Sarah J. Maas','Não Ficção'),
	('Rebelde','Amy Tintera','Suspense'),
	('Ídolos','Margaret Stohl','Sci-Fi'),
	('Zumbeatles','Alan Goldsher','Mistério'),
	('Três Chances','Alexandra Bullen','Fantasia'),
	('Nunca Jamais','Colleen Hoover','Ficção'),
	('Outro Dia','David Levithan','Fantasia'),
	('De Volta','Kass Morgan','Suspense'),
	('Imaculada','Kami Garcia','Fantasia'),
	('Dama da Meia-Noite','Cassandra Clare','Romace'),
	('A Profecia do Paladino.','Mark Frost','Mistério'),
	('Vamos juntas?','Babi Souza','Não Ficção'),
	('O Código da Atração','Pamela Wells','Aventura'),
	('Rainha das Sombras','Sarah J. Maas','Suspense'),
	('O Livro de Cam','Lauren Kate','Ficção'),
	('The Originals - A Perda','Julie Plec','Suspense'),
	('Outro Conto Sombrio Dos Grimm','Adam Gidwitz','Fantasia'),
	('O Preço do Sangue','Justin Somper','Não Ficção'),
	('Corte de Névoa e Fúria','Sarah J. Maas','Ficção'),
	('O Chamado','Michael Grant','Aventura'),
	('Tudo ou Nada','Sarah Mlynowski','Mistério'),
	('Yakuba','Thierry Dedieu','Mistério'),
	('O Círculo','Cate Tiernan','Mistério'),
	('Problemas na Vila Zumbi','Mark Cheverton','Fantasia'),
	('O Caderninho de Desafios de Dash e Lily','David Levithan','Suspense'),
	('Os Feiticeiros da Tempestade','Philippa Gregory','Sci-Fi'),
	('A Pedra Proibida','Tony Abbott','Fantasia'),
	('Talvez Um Dia','Colleen Hoover','Mistério'),
	('Além-Mundos','Scott Westerfeld','Aventura'),
	('Warcraft - Durotan','Christie Golden','Não Ficção'),
	('Warcraft','Christie Golden','Mistério'),
	('Silêncio','Richelle Mead','Romace'),
	('O Amor nos Tempos de #Likes','Pam Gonçalves','Suspense'),
	('A Geografia de Nós Dois','Jennifer E. Smith','Não Ficção'),
	('De Volta a Blackbrick','Sarah Moore Fitzgerald','Não Ficção'),
	('Princesa das Águas','Paula Pimenta','Fantasia'),
	('Um Mundo Melhor','Marcus Sakey','Fantasia'),
	('A Caçadora de Bruxos',' Virginia Boecker','Sci-Fi'),
	('Lembrança','Meg Cabot','Não Ficção'),
	('Noites Roubadas','Rebecca Maizel','Aventura'),
	('O Filho da feiticeira','Kelly Barnhill','Ficção'),
	('A Revolução do Carrasco','Eoin Colfer','Aventura'),
	('Diários de Stefan - Asilo','L. J. Smith','Suspense'),
	('A Garota Gotic e o Festival mais Assustador que a Morte','Chris Riddell','Mistério'),
	('Magônia',' Maria Dahvana Headley','Ficção'),
	('George','Alex Gino','Não Ficção'),
	('Boomerang','Noelle August','Sci-Fi'),
	('Illidan','William King','Mistério'),
	('Diário de Uma Princesa Improvável','Meg Cabot','Mistério'),
	('Boa Noite','Pam Gonçalves','Sci-Fi'),
	('Confissões de Um Amigo Imaginário','Michelle Cuevas','Aventura'),
	('Caindo na Real','Jen Calonita','Mistério'),
	('A esperança é uma Torta de Maçã','Sarah Moore Fitzgerald','Não Ficção'),
	('Lúcida','Ron Bass e Adrienne Stoltz','Ficção'),
	('Novembro, 9','Colleen Hoover','Romace'),
	('Harry Potter - O Livro dos Artefatos Mágicos','Jody Revenson','Suspense'),
	('Filha das Trevas','Kelly Keaton','Sci-Fi'),
	('Animais Fantásticos e Onde Habitam','Rick Barba','Sci-Fi'),
	('Revolta em Nova York','Matthew J. Kirby','Sci-Fi'),
	('MacBeth','William Shakespeare','Ficção'),
	('O Bosque Subterrâneo',' Colin Meloy','Mistério'),
	('O Guia Para Ser Você Mesma','Mel Souza','Ficção'),
	('O Oráculo do Templo da Selva','Mark Cheverton','Não Ficção'),
	('A Chave de Bronze','Cassandra Clare','Mistério'),
	('Uma História de Notáveis Caçadores de Sombras e Seres do Submundo','Cassandra Clare','Ficção'),
	('Fallen','Lauren Kate','Aventura'),
	('A Traição de Natalie Hargrove','Lauren Kate','Sci-Fi'),
	('Golias: A Revelação','Scott Westerfeld','Não Ficção'),
	('Unity','Oliver Bowden','Aventura'),
	('Sem Esperança','Colleen Hoover','Aventura'),
	('Amy & Matthew','Cammie McGovern','Não Ficção'),
	('Dilúvio','Lauren Kate','Ficção'),
	('Reboot','Amy Tintera','Romace'),
	('Uma Vez','Anna Carey','Romace'),
	('O Crime Mais Que Perfeito','Carlos Heitor Cony','Suspense'),
	('As Confissões das Irmãs Sullivan','Natalie Standiford','Aventura'),
	('Dia 21','Kass Morgan','Mistério'),
	('Destino','L. J. Smith','Romace'),
	('O para sempre de Pedrina e Tunico','Claudio Fragata','Não Ficção'),
	('Síndrome Psíquica Grave','Alicia Thompson','Fantasia'),
	('Não-Sei-Quê','Stefan Bachmann','Suspense'),
	('Dois Garotos Se Beijando','David Levithan','Não Ficção'),
	('Férias Infernais (Vacations from hell)','Maureen Johnson','Sci-Fi'),
	('Uma História de Amor e TOC','Corey Ann Haydu','Aventura'),
	('Quebrando As Regras','Joanna Philbin','Ficção'),
	('Cinderela Pop','Paula Pimenta','Mistério'),
	('A Espada de Atilla','David Gibbins','Não Ficção'),
	('Declínio','Jay Bonansinga','Romace'),
	('O Voo Negro dos Corvos','Fabien Nury','Mistério'),
	('Contos de Fadas em Quadrinhos',' Chris Duffy','Sci-Fi'),
	('Blecaute','John Rocco','Aventura'),
	('A Lâmina da Assassina','Sarah J. Maas','Aventura'),
	('O Substituto','Philippa Gregory','Fantasia'),
	('Brilhantes','Marcus Sakey','Sci-Fi'),
	('Invasão do Mundo da Superfície','Mark Cheverton','Fantasia'),
	('Um Conto Sombrio dos Grimm','Adam Gidwitz','Sci-Fi'),
	('Dias Infinitos','Rebecca Maizel','Mistério'),
	('Elena - A Filha da Princesa','Marina Carvalho','Fantasia'),
	('A pequena Alice no País das Maravilhas','Lewis Carroll','Mistério'),
	('Livro das Sombras','Cate Tiernan','Sci-Fi'),
	('Corações de Alcachofra','Sita Brahmachari','Fantasia'),
	('Se O Sapatinho Servir','Sarah Mlynowski','Romace'),
	('As 13 Chaves','Eliane Ganem','Fantasia'),
	('The Originals - Ascensão','Julie Plec','Aventura'),
	('Tesourinha e A Bruxa','Diana Wynne Jones','Mistério'),
	('Dead Island','Mark Morris','Mistério'),
	('Gatos: O Livro de Colorir','Marjorie Sarnat','Fantasia'),
	('REVIRAVENTO','Silvana Tavano','Sci-Fi'),
	('Fator Nerd: Missão Improvável','Andy Robb','Ficção'),
	('A Fofa do Terceiro Andar','Cléo Busatto','Não Ficção'),
	('Fogo da Fúria','T.A. Barron','Romace'),
	('Jornada','Aaron Becker','Ficção'),
	('Meninos, Eu Conto','Antônio Torres','Mistério'),
	('Ela Não é Invisível','Marcus Sedgwick','Ficção'),
	('Naomi & Ely e a Lista do Não-Beijo','David Levithan','Mistério'),
	('Ateliê Fashion: Estampas Para Colorir','Rafaella Machado','Sci-Fi'),
	('The Walking Dead','Jay Bonansinga','Sci-Fi');
INSERT INTO livro_livros (titulo, autor, genero) VALUES ('Magia','Andrea Camilleri','Fantasia'),
	('Rich e Mad','William Nicholson','Suspense'),
	('Em Busca de Cinderela','Colleen Hoover','Não Ficção'),
	('A Garota Gotic e O Fantasma de um Rato','Chris Riddell','Aventura'),
	('Herdeira do Fogo','Sarah J. Maas','Suspense'),
	('No Início Não Havia Bob','Meg Rosoff','Aventura'),
	('À Procura de Audrey','Sophie Kinsella','Fantasia'),
	('As Herdeiras Tomam O Palco','Joanna Philbin','Aventura'),
	('A Vingança de Mara Dyer','Michelle Hodkin','Não Ficção'),
	('Os Lugares Mágicos dos Filmes de Harry Potter','Jody Revenson','Não Ficção'),
	('Diários de Stefan - Estripador','Aubrey Clark','Suspense'),
	('O Lado Feio do Amor','Colleen Hoover','Suspense'),
	('O Vitral Encantado','Diana Wynne Jones','Romace'),
	('O Aprendiz','Taran Matharu','Aventura'),
	('Batalha Pelo Nether','Mark Cheverton','Sci-Fi'),
	('Vidas Secas: Graphic Novel','Graciliano Ramos','Sci-Fi'),
	('Despertar','Meg Cabot','Fantasia'),
	('Incubus','Margaret Stohl','Fantasia'),
	('Assassin''s Creed: Unity: Abstergo Entertainment - Dossiê do Funcionário','Christie Golden','Aventura'),
	('Me Abrace Mais Forte','David Levithan','Ficção'),
	('A Ruptura','Aubrey Clark','Não Ficção'),
	('A Luva de Cobre','Cassandra Clare','Não Ficção'),
	('O Casamento da Princesa','Meg Cabot','Aventura'),
	('O Diário da Princesa','Meg Cabot','Fantasia'),
	('Um Dia Existimos','Kat Zhang','Não Ficção'),
	('De Volta ao Presente','Meg Cabot','Fantasia'),
	('O Livro dos Personagens de Harry Potter','Jody Revenson','Ficção'),
	('Cidade de Vidro e Cidade dos Anjos Caídos','Cassandra Clare','Aventura'),
	('Assassin''s Creed: Submundo','Oliver Bowden','Mistério'),
	('O Livro Do Feromonas','Miguel Campos','Romace'),
	('Enfrentando O Dragão','Mark Cheverton','Suspense'),
	('Faísca','Antonio Skármeta','Suspense'),
	('Sorria, você está sendo iluminado!','Felipe Guga','Romace'),
	('E o Vento Levou','Margaret Mitchell','Romace'),
	('As crônicas de Bane','Cassandra Clare','Romace'),
	('O Lado Feio do Amor','Colleen Hoover','Aventura'),
	('Me Abrace Mais Forte','David Levithan','Ficção'),
	('cidade das almas perdidas','Cassandra Clare','Não Ficção'),
	('Todo Garoto Tem','Meg Cabot','Ficção'),
	('Cidade das Cinzas','Cassandra Clare','Suspense'),
	('O Sacrifício','Rachel Hawkins','Romace'),
	('A Princesa no Limite','Meg Cabot','Fantasia'),
	('A Princesa em Treinamento','Meg Cabot','Romace'),
	('A Princesa na Balada','Meg Cabot','Aventura'),
	('Cidade das Almas Perdidas','Cassandra Clare','Suspense'),
	('Princesa Mia','Meg Cabot','Romace'),
	('O Bosque Selvagem',' Colin Meloy','Fantasia'),
	('Cidade do Fogo Celestial','Cassandra Clare','Não Ficção'),
	('The Walking Dead','Robert Kirkman','Mistério'),
	('Emily, The Strange: Duas Vezes Estranha','Rob Reger','Fantasia'),
	('Duelo Ao Luar','Andrea Cremer','Suspense'),
	('Casa de Segredos','Ned Vizzini','Romace'),
	('Aquilus','Corbeyran','Mistério'),
	('A Viagem de Íris','Gill Lewis','Ficção'),
	('Flash Forward','Robert J. Sawyer','Ficção'),
	('Sempre Teremos o Verão','Jenny Han','Fantasia'),
	('O Códex dos Caçadores de Sombras','Cassandra Clare','Romace'),
	('O Livro dos Mil Dias','Shannon Hale','Suspense'),
	('Desejos','Alexandra Bullen','Mistério'),
	('The 100: Os Escolhidos','Kass Morgan','Não Ficção'),
	('Alvorada dos Aspectos','Richard A. Knaak','Aventura'),
	('Me Dê Uma Chance','Cecily von Ziegesar','Suspense'),
	('O Livro dos Vilões','Carina Rissi','Suspense'),
	('Demônios do Paraíso','William C. Dietz','Romace'),
	('Limbo','Anthony Horowitz','Mistério'),
	('Don Juan','Alessandro Baricco','Não Ficção'),
	('A história de O Nariz','Andrea Camilleri','Ficção'),
	('Will & Will','John Green','Mistério'),
	('Cidade de Vidro','Cassandra Clare','Ficção'),
	('Inferno','Meg Cabot','Sci-Fi'),
	('Diário de Uma Treinadora de Pais','Jenny Smith','Não Ficção'),
	('Santuário','Meg Cabot','Não Ficção'),
	('Um Caso Perdido','Colleen Hoover','Aventura'),
	('Canção da Lua','L. J. Smith','Aventura'),
	('Tempestade de Luz','Nate Kenyon','Romace'),
	('Sonho Perigoso','Margaret Stohl','Aventura'),
	('Garota em Foco','Cecily von Ziegesar','Mistério'),
	('Princesa Adormecida','Paula Pimenta','Suspense'),
	('A Evolução de Mara Dyer','Michelle Hodkin','Suspense'),
	('O Círculo','Kieran Scott','Fantasia'),
	('Anjos Na Escuridão','Lauren Kate','Sci-Fi'),
	('Inimigo Sombrio','Cate Tiernan','Sci-Fi'),
	('O Peculiar','Stefan Bachmann','Sci-Fi'),
	('Se alguma vez...','Meg Rosoff','Sci-Fi'),
	('Invisível','David Levithan','Romace'),
	('Battlefield 4: Contagem Regressiva','Peter Grimsdale','Romace'),
	('Homero','Luiz Antonio Aguiar','Ficção'),
	('Assassin''s Creed: Barba Negra - O Diário Perdido','Christie Golden','Aventura'),
	('Confesso Que Menti','Justine Larbalestier','Suspense'),
	('Ai Meus Deuses!','Tera Lynn Childs','Sci-Fi'),
	('Coroa da Meia-Noite','Sarah J. Maas','Ficção'),
	('O Que Restou de Mim','Kat Zhang','Fantasia'),
	('Medo','Michael Grant','Romace'),
	('O Condado de Citrus','John Brandon','Sci-Fi'),
	('Inquebrável','Kami Garcia','Sci-Fi'),
	('Garoto Encontra Garoto','David Levithan','Suspense'),
	('Essa Garota','Colleen Hoover','Não Ficção'),
	('Petra do coração de pedra','Anna Claudia Ramos','Mistério'),
	('Cidade dos Ossos e Cidade das Cinzas','Cassandra Clare','Aventura'),
	('O Assassino Relutante','Eoin Colfer','Romace'),
	('Alma da Fera (Ascendant)','Diana Peterfreund','Mistério'),
	('Onde Deixarei Meu Coração','Sarra Manning','Suspense'),
	('The Walking Dead','Robert Kirkman','Aventura'),
	('Ser Feliz é Assim','Jennifer E. Smith','Mistério'),
	('O Livro das Criaturas de Harry Potter','Jody Revenson','Suspense'),
	('Longe de Você','Emily Hainsworth','Ficção'),
	('Crimes de Guerra','Christie Golden','Mistério'),
	('Livro de Tyrael','Matt Burns','Suspense'),
	('Mass Effect: Ascensão','Drew Karpyshyn','Romace'),
	('VIII','H. M. Castor','Mistério'),
	('Prisioneira da Inquisição','Theresa Breslin','Fantasia'),
	('As Crônicas de Bane','Cassandra Clare','Fantasia'),
	('Ícones','Margaret Stohl','Mistério'),
	('A Mais Bela de Todas','Sarah Mlynowski','Romace'),
	('Garotas, Glitter e a Grande Fraude','Meg Cabot','Suspense'),
	('Sirena','Margaret Stohl','Não Ficção'),
	('A Noiva é Tamanho 42','Meg Cabot','Não Ficção'),
	('Crepúsculo dos Aspectos','Christie Golden','Suspense'),
	('A Batalha das Bestas','Ned Vizzini','Aventura'),
	('Aliens de Férias','Clete Barrett Smith','Ficção'),
	('O Palhaço Está em Greve','Marco Túlio Costa','Suspense'),
	('Will & Will','John Green','Fantasia'),
	('Tormenta','Lauren Kate','Sci-Fi'),
	('Êxtase','Lauren Kate','Romace'),
	('Um caso perdido','Collen Hoover','Romace'),
	('Feios','Scott Westerfeld','Fantasia'),
	('Tamanho Não Importa','Meg Cabot','Suspense'),
	('Dezessete Luas','Margaret Stohl','Aventura'),
	('Extras','Scott Westerfeld','Suspense'),
	('Príncipe Mecânico','Cassandra Clare','Mistério'),
	('Sortilégio','Rachel Hawkins','Ficção'),
	('Glee - Férias de Verão','Galera Record','Romace'),
	('Sem Você Não é Verão','Jenny Han','Suspense'),
	('Princesa Mecânica','Cassandra Clare','Romace'),
	('A Vingança Veste Prada','Lauren Weisberger','Não Ficção'),
	('Princesa Para Sempre','Meg Cabot','Mistério'),
	('Dezoito Luas','Kami Garcia','Aventura'),
	('Cair das Trevas','Cate Tiernan','Fantasia'),
	('A Probabilidade Estatística do Amor à Primeira Vista','Jennifer E. Smith','Mistério'),
	('Na Passarela','Meg Cabot','Aventura'),
	('Gregor e o Código da Garra','Suzanne Collins','Não Ficção'),
	('The Walking Dead','Robert Kirkman','Suspense'),
	('A Maldição','Rachel Hawkins','Não Ficção'),
	('Assassin''s Creed: Revelações','Oliver Bowden','Suspense'),
	('Dezesseis Luas','Kami Garcia','Fantasia'),
	('O Morto','Charlie Higson','Suspense'),
	('Mentirinhas Inocentes','Lauren Conrad','Fantasia'),
	('Furacão Dourado','Charlie Higson','Fantasia'),
	('Confissões','Kieran Scott','Sci-Fi'),
	('Eona','Alison Goodman','Romace'),
	('O Caminho Para Woodbury','Robert Kirkman','Não Ficção'),
	('O Futuro de Nós Dois','Jay Asher','Mistério'),
	('Ponto Crítico','Christie Golden','Sci-Fi'),
	('O Livro das Princesas','Paula Pimenta','Não Ficção'),
	('Floresta Sombria','Matt Haig','Aventura'),
	('Hollywood É Como A Escola','Zoey Dean','Aventura'),
	('Garotos, Garotas e Outros Materiais Explosivos','Rosalind Wiseman','Aventura'),
	('Dezesseis Luas (Beautiful Creatures)','Kami Garcia','Aventura'),
	('O Poder','L. J. Smith','Não Ficção'),
	('Will & Will','John Green','Fantasia'),
	('Garotas, Surpresas e Segredos','Cecily von Ziegesar','Sci-Fi'),
	('A Sociedade Cinderela','Kay Cassidy','Não Ficção'),
	('A Tempestade','William Shakespeare','Fantasia'),
	('Dezenove Luas','Kami Garcia','Suspense'),
	('Abandono','Meg Cabot','Fantasia'),
	('Sociedade Cinderela','Cassidy','Romace'),
	('Esconderijo seguro','Meg Cabot','Fantasia'),
	('Se Você Está Lendo Este Livro É Tarde Demais','Pseudonymous Bosch','Sci-Fi'),
	('Lágrima','Lauren Kate','Fantasia'),
	('Espectro','L. J. Smith','Romace'),
	('Como Dizer Adeus em Robô','Natalie Standiford','Aventura'),
	('A Ruptura','Christie Golden','Aventura'),
	('Métrica','Colleen Hoover','Aventura'),
	('Abandonada','Meg Cabot','Sci-Fi'),
	('Diablo III: Livro de Cain','Flint Dille','Sci-Fi'),
	('10 Coisas Que Nós Fizemos','Sarah Mlynowski','Sci-Fi'),
	('Garota, 15 anos, Lindas, Porém Louca','Sue Limb','Sci-Fi'),
	('Beemote: A Revolução','Scott Westerfeld','Aventura'),
	('Todo Dia','David Levithan','Aventura'),
	('Trono de Vidro','Sarah J. Maas','Aventura'),
	('Caçadora de Unicórnios','Diana Peterfreund','Não Ficção'),
	('A Desconstrução de Mara Dyer','Michelle Hodkin','Sci-Fi'),
	('Esconderijo Perfeito','Meg Cabot','Sci-Fi'),
	('Poseur - Boazinhas, Glamourosas e Feias','Rachel Maude','Mistério'),
	('Sombras da Horda','Michael A. Stackpole','Fantasia'),
	('As Irmãs Sloane 2','Anna Carey','Mistério'),
	('A Misteriosa Sociedade Benedict e A Jornada Periculosa','Trenton Lee Stewart','Sci-Fi'),
	('Gulliver','Jonathan Coe','Aventura'),
	('Fator Nerd: Contatos Imediatos do 1º Amor','Andy Robb','Ficção'),
	('Praga','Michael Grant','Não Ficção'),
	('Limiar','Jessica Warman','Mistério'),
	('Guerra Imortal','Justin Somper','Aventura'),
	('Revelação','Drew Karpyshyn','Ficção'),
	('Medo de Palco','Meg Cabot','Fantasia'),
	('O Último Guardião','Eoin Colfer','Fantasia'),
	('Pausa','Colleen Hoover','Fantasia'),
	('Outras Palavras Para O Amor','Lorraine Zago Rosenthal','Fantasia'),
	('Polícia Paranormal','Kiersten White','Suspense'),
	('Rome','David Gibbins','Fantasia'),
	('Espiral da Morte','Derek Landy','Romace'),
	('Fallen','Lauren Kate','Aventura'),
	('Paixão','Lauren Kate','Mistério'),
	('Tamanho 42 e Pronta Para Arrasar','Meg Cabot','Romace'),
	('As Regras do Amor','Pamela Wells','Romace'),
	('Tempo em Fúria','Myra McEntire','Não Ficção'),
	('Espiãs Se Arriscam em Dobro','Ally Carter','Ficção'),
	('99 Séries Clássicas Para Apressadinhos','Thomas Wengelewski','Ficção'),
	('Strawberry Fields Forever','Richard Zimler','Suspense'),
	('Assassin''s Creed: Bandeira Negra','Oliver Bowden','Romace'),
	('Eva','Anna Carey','Mistério'),
	('Diários de Stefan - Desejo','L. J. Smith','Fantasia'),
	('Êxtase','Lauren Kate','Aventura'),
	('Apaixonados','Lauren Kate','Mistério'),
	('Trono de vidro','Sarah J. Maas','Sci-Fi'),
	('Cidade das Cinzas','Cassandra Clare','Mistério'),
	('Cidade das Almas Perdidas','Cassandra Clare','Aventura'),
	('Tamanho 44 Também não é Gorda','Meg Cabot','Romace'),
	('Tamanho não Importa','Meg Cabot','Fantasia'),
	('Tamanho 42 e Pronta pra Arrasar','Meg Cabot','Não Ficção'),
	('Filhas da Escuridão','L. J. Smith','Romace'),
	('Cabeça de Vento','Meg Cabot','Aventura'),
	('Dias Sombrios','Derek Landy','Romace'),
	('A Fúria','L. J. Smith','Fantasia'),
	('Festas & Poções','Sarah Mlynowski','Não Ficção'),
	('Meia-Noite','L. J. Smith','Sci-Fi'),
	('Insaciável','Meg Cabot','Ficção'),
	('Anjo Mecânico','Cassandra Clare','Mistério'),
	('Sendo Nikki','Meg Cabot','Aventura'),
	('O Ramo de Prata','Rosemary Sutcliff','Romace'),
	('Irmandade','Oliver Bowden','Sci-Fi'),
	('Assassin''s Creed: A Cruzada Secreta','Oliver Bowden','Romace'),
	('O Verão e a Cidade','Candace Bushnell','Ficção'),
	('A Trilha da Lua Cheia','Tabajara Ruas','Não Ficção'),
	('Você Nunca se Satisfaz','Cecily von Ziegesar','Fantasia'),
	('A Prisioneira','L. J. Smith','Fantasia'),
	('Intocáveis','Kieran Scott','Mistério'),
	('Codinome Cassandra','Meg Cabot','Aventura'),
	('Alice de novo','Judi Curtin','Ficção'),
	('The Walking Dead','Robert Kirkman','Não Ficção'),
	('Nos Bastidores da TV','Carlos Heitor Cony','Mistério'),
	('A Última Princesa','Fábio Yabu','Aventura'),
	('Mordida','Meg Cabot','Romace'),
	('Tom Coração Leal e a Terra das Histórias Sombrias','Ian Beck','Romace'),
	('O fio da palavra','Bartolomeu Campos de Queirós','Romace'),
	('Garotas em Festa','Cecily von Ziegesar','Não Ficção'),
	('Nas sombras','Jeri Smith-Ready','Sci-Fi'),
	('Meu livrinho vermelho','Rachel Kauder Nalebuff','Fantasia'),
	('Segredos de amor, namoro e paixão','Pedro Bandeira','Aventura'),
	('Império da Noite','Justin Somper','Não Ficção'),
	('SEGREDOS DE AMOR, NAMORO E PAIXÃO (VOL. 3)','Leo Cunha','Ficção');
INSERT INTO livro_livros (titulo, autor, genero) VALUES ('Glee - Câmbio Exterior','Sophia Lowell','Suspense'),
	('Apaixonados','Lauren Kate','Aventura'),
	('Gregor e as Marcas Secretas','Suzanne Collins','Mistério'),
	('Festas & Poções','Sarah Mlynowski','Ficção'),
	('Nós Somos os Senhores do Clima','Tim Flannery','Romace'),
	('O livro perigoso para garotos (de bolso)','Conn Iggulden','Não Ficção'),
	('Maçãs Envenenadas','Lily Archer','Aventura'),
	('Minha Vida Agora','Meg Rosoff','Não Ficção'),
	('Battlefield 3','Andy McNab','Romace'),
	('Lua de Sangue','Andrea Cremer','Fantasia'),
	('Espiãs Também Se Enganam','Ally Carter','Suspense'),
	('Diários de Stefan - Sede de Sangue','L. J. Smith','Mistério'),
	('As Nove Vidas de Chloe King: Banidos','Liz Braswell','Fantasia'),
	('Garotos Malditos','Santiago Nazarian','Não Ficção'),
	('Um conto de fadas em Manhattan','Elisa Puricelli Guerra','Ficção'),
	('Bum!','Mark Haddon','Suspense'),
	('A roda do vento','Nélida Piñon','Fantasia'),
	('Leviatã: A Missão Secreta','Scott Westerfeld','Aventura'),
	('Amada Imortal','Cate Tiernan','Ficção'),
	('Zumbis x Unicórnios','Holly Black','Suspense'),
	('Psycho Killer','Cecily von Ziegesar','Aventura'),
	('Resident Evil','John Shirley','Suspense'),
	('Segredos da Minha Vida em Hollywood: Princesa Paparazzi','Jen Calonita','Sci-Fi'),
	('Artemis Fowl','Eoin Colfer','Ficção'),
	('Mentiras','Michael Grant','Sci-Fi'),
	('As 17 cores do branco','Lauz Raul Machado','Sci-Fi'),
	('Diablo III: A Ordem','Nate Kenyon','Suspense'),
	('Marés da Guerra','Christie Golden','Sci-Fi'),
	('Escolhas de Formatura','Diana Peterfreund','Não Ficção'),
	('O Livro Perigoso para Garotos (de bolso) vol. 1','Conn Iggulden','Ficção'),
	('Renegado','Oliver Bowden','Aventura'),
	('Cinema Pirata','Cory Doctorow','Suspense'),
	('Amor Contra o Tempo','Myra McEntire','Sci-Fi'),
	('O Acaçá de Cada Um','Celso Sisto','Ficção'),
	('Gregor e a Segunda Profecia','Suzanne Collins','Aventura'),
	('Diários de Stefan - Sede de sangue','L. J. Smith','Mistério'),
	('Mwindo','André Diniz','Fantasia'),
	('Feios','Scott Westerfeld','Suspense'),
	('Cidade de Vidro','Cassandra Clare','Ficção'),
	('Sociedade Secreta: Escolhas de Formatura','Diana Peterfreund','Aventura'),
	('A História de Os Noivos','Umberto Eco','Aventura'),
	('O Bebê Comprado do Bilionario','Sophia Lynn','Ficção'),
	('Cidade dos Ossos','Cassandra Clare','Ficção'),
	('Almas Sombrias','L. J. Smith','Suspense'),
	('A Rainha da Fofoca - Fisgada','Meg Cabot','Romace'),
	('Assassin''s Creed: Renascença','Oliver Bowden','Romace'),
	('Tormenta','Lauren Kate','Fantasia'),
	('Vampiro Secreto','L. J. Smith','Romace'),
	('Emily, The Strange: Os Dias Perdidos','Rob Reger','Sci-Fi'),
	('Fome','Michael Grant','Romace'),
	('Quando Cai o Raio','Meg Cabot','Ficção'),
	('Hex Hall','Rachel Hawkins','Sci-Fi'),
	('Os Radley','Matt Haig','Sci-Fi'),
	('A Sociedade Secreta dos O.U.T.R.O.S.','Pedro Mañas','Romace'),
	('Xeque-Mate','Malorie Blackman','Não Ficção'),
	('Amores Infernais','Scott Westerfeld','Mistério'),
	('Otolina na escola','Chris Riddell','Fantasia'),
	('A Fera','Alex Flinn','Não Ficção'),
	('Paixão','Lauren Kate','Ficção'),
	('Liberte Meu Coração','Meg Cabot','Sci-Fi'),
	('Eu Sempre Vou Te Amar','Cecily von Ziegesar','Ficção'),
	('Eon - O Décimo Segundo Dragão','Alison Goodman','Fantasia'),
	('A Guerra da Pólvora Negra','Naomi Novik','Romace'),
	('Hamlet','William Shakespeare','Aventura'),
	('Romeu e Julieta','William Shakespeare','Sci-Fi'),
	('A Profecia de Nostradamus','Theresa Breslin','Mistério'),
	('Eu Sou Um Gênio de Maldade Inenarrável e Quero Ser Seu Presidente de Turma','Josh Lieb','Aventura'),
	('Grana ou Drama','Grace Dent','Não Ficção'),
	('Rostinho Bonito','Mary Hogan','Aventura'),
	('Garota dos Sonhos','Lauren Mechling','Ficção'),
	('Diários de Stefan - Origens','L. J. Smith','Sci-Fi'),
	('Glee - O Início','Sophia Lowell','Sci-Fi'),
	('Gregor e a Profecia de Sangue','Suzanne Collins','Sci-Fi'),
	('O Complexo de Atlântida','Eoin Colfer','Aventura'),
	('Pequeno Irmão','Cory Doctorow','Mistério'),
	('A Iniciação','L. J. Smith','Sci-Fi'),
	('As Irmãs Sloane','Anna Carey','Não Ficção'),
	('99 filmes clássicos para apressadinhos','Henrik Lange','Não Ficção'),
	('Cowboys & Aliens','Fred Van Lente','Fantasia'),
	('Cowboys & Aliens','Joan D. Vinge','Ficção'),
	('Uma Ilha no Oceano','Annika Thor','Não Ficção'),
	('Assinado, Mata Hari','Yannic Murphy','Ficção'),
	('Sob a Luz da Lua','Andrea Cremer','Mistério'),
	('L.A. Candy','Lauren Conrad','Fantasia'),
	('Melhores Amigas Para Sempre','Meg Cabot','Sci-Fi'),
	('Chitty Chitty Bang Bang: o carro mágico','Ian Fleming','Aventura'),
	('Necropólis','Anthony Horowitz','Sci-Fi'),
	('O Protocolo Soberano','Mark Walden','Mistério'),
	('A Mecânica do Coração','Mathias Malzieu','Mistério'),
	('12 de setembro','Jean-Christophe Ogier','Suspense'),
	('Com Louvor','Cecily von Ziegesar','Ficção'),
	('Era uma vez à meia-noite','Aguiar','Ficção'),
	('Cidade dos Anjos Caídos','Cassandra Clare','Fantasia'),
	('Marcelo no Mundo Real','Francisco X. Stork','Romace'),
	('O Verão Que Mudou Minha Vida','Jenny Han','Romace'),
	('Footloose','Rudy Josephs','Romace'),
	('Beijos Infernais (Kisses from hell)','Kristin Cast','Suspense'),
	('Ricardo III','William Shakespeare','Não Ficção'),
	('Tollins 2 - Histórias que são pura dinamite','Conn Iggulden','Aventura'),
	('Tollins 2 - Histórias que são pura dinamite','Conn Iggulden','Suspense'),
	('O MISTÉRIO DO FEITICEIRO - SHERLOCK HOLMES E OS IRREGULARES DE BAKER STREET, VOL. 2','Tracy Mack','Aventura'),
	('Cidade de Vidro','Cassandra Clare','Não Ficção'),
	('Formaturas Infernais (Prom nights from hell)','Meg Cabot','Ficção'),
	('Só Para Convidados','Kieran Scott','Ficção'),
	('A Fúria','L. J. Smith','Romace'),
	('Reunião Sombria','L. J. Smith','Não Ficção'),
	('A modelo do ano','Carol Alt','Aventura'),
	('Tênis ou Tiaras','Grace Dent','Aventura'),
	('Ela Foi Até o Fim','Meg Cabot','Mistério'),
	('O vampiro não está tão afim de você','Vlad Mezrich','Ficção'),
	('Cupcake','Rachel Cohn','Romace'),
	('Garota de Sorte','Cecily von Ziegesar','Suspense'),
	('Casaco Marrom','Giselle Nogueira','Fantasia'),
	('O Diário da Princesa','Meg Cabot','Romace'),
	('Princesa Sob os Refletores','Meg Cabot','Ficção'),
	('Dezesseis Luas','Kami Garcia','Suspense'),
	('TOM CORAÇÃO LEAL','Ian Beck','Não Ficção'),
	('Quem matou o livro policial?','Luiz Antonio Aguiar','Romace'),
	('Barbara Debaixo Da Chuva','NILMA GONÇALVES LACERDA','Fantasia'),
	('O Quilombo Orum Aiê','André Diniz','Mistério'),
	('Gone','Michael Grant','Romace'),
	('Os Diários de Carrie','Candace Bushnell','Não Ficção'),
	('Academia de Princesas','Shannon Hale','Aventura'),
	('Louras Zumbis','Brian James','Aventura'),
	('Principe da Pérsia','Jordan Mechner','Ficção'),
	('A Águia da Nona','Rosemary Sutcliff','Romace'),
	('Segredos da Minha Vida em Hollywood - Negócios de Família','Jen Calonita','Mistério'),
	('90 Livros Clássicos para Apressadinhos','Henrik Lange','Mistério'),
	('A Garota Nova','Meg Cabot','Mistério'),
	('Fallen','Lauren Kate','Suspense'),
	('Gregor e a Segunda Profecia','Suzanne Collins','Romace'),
	('Anoitecer','L. J. Smith','Ficção'),
	('Dominando a Tempestade','Salamanda Drake','Mistério'),
	('Garota Quase 15 anos, Paquerando pela Inglaterra','Sue Limb','Não Ficção'),
	('Garota em Tentação','Cecily von Ziegesar','Romace'),
	('Kiki de Montparnasse','Catel & Bocquet','Aventura'),
	('Os Sem-Rosto','Derek Landy','Não Ficção'),
	('O Círculo de Ouro','Guillaume Prévost','Ficção'),
	('A Misteriosa Sociedade Benedict','Trenton Lee Stewart','Mistério'),
	('Coração Negro','Justin Somper','Ficção'),
	('Pérolas ou Pegas','Grace Dent','Suspense'),
	('Espiã Para Sempre','Ally Carter','Ficção'),
	('O Nome Deste Livro É Segredo','Pseudonymous Bosch','Suspense'),
	('A Casa dos Muitos Caminhos','Diana Wynne Jones','Romace'),
	('Pânico na estrada','Eoin Colfer','Ficção'),
	('O Vingador','Andy McNab','Romace'),
	('O Trono de Jade','Naomi Novik','Sci-Fi'),
	('O Diário da Princesa','Meg Cabot','Ficção'),
	('O Estranho Sumiço do Morcego','Tania Zagury','Fantasia'),
	('O livro perigoso para garotos (de bolso)','Conn Iggulden','Aventura'),
	('Cidade dos Ossos','Cassandra Clare','Sci-Fi'),
	('As Delícias da Fofoca','Cecily von Ziegesar','Ficção'),
	('Liga-me','Sarah Mlynowski','Aventura'),
	('Sob a Rosa','Diana Peterfreund','Não Ficção'),
	('Nick & Norah','Rachel Cohn','Aventura'),
	('Os Últimos Dias','Scott Westerfeld','Mistério'),
	('Pegando Fogo!','Meg Cabot','Aventura'),
	('As Sete Moedas','Guillaume Prévost','Aventura'),
	('Um Beijo Para Valer','Mary Hogan','Suspense'),
	('Só Podia Ser Você: O Início','Cecily von Ziegesar','Sci-Fi'),
	('Brincando com Fogo','Derek Landy','Não Ficção'),
	('Sidarta para jovens','Bruno Pacheco','Sci-Fi'),
	('Dia da Mudança','Meg Cabot','Suspense'),
	('O Despertar','L. J. Smith','Romace'),
	('Poseur - Brigas, Garotos e Estilo','Rachel Maude','Mistério'),
	('Princesa Para Sempre','Meg Cabot','Fantasia'),
	('Sr. Gum e o Biscoito Bilionário','Andy Stanton','Não Ficção'),
	('Capitão de Sangue','Justin Somper','Não Ficção'),
	('Segredos Roubados','Rosana Rios','Aventura'),
	('O Monstro da Lagoa de Abaeté','Anna Lee','Não Ficção'),
	('Atherton - A Casa do Poder','Patrick Carman','Suspense'),
	('Exclusivo','Kieran Scott','Sci-Fi'),
	('O livro negro dos segredos','F. E. Higgins','Mistério'),
	('Criança pensa','Lya Luft','Suspense'),
	('O Confronto','L. J. Smith','Não Ficção'),
	('Tamanho 44 Também Não é Gorda','Meg Cabot','Não Ficção'),
	('Derby Girl','Shauna Cross','Fantasia'),
	('Escola de Espiãs','Ally Carter','Aventura'),
	('A Música Que Mudou Minha Vida','Robin Benway','Suspense'),
	('Kiki Strike e a Tumba da Imperatriz','Kirsten Miller','Romace'),
	('C.O.V.A.','Mark Walden','Ficção'),
	('Aviador','Eoin Colfer','Romace'),
	('Diário absolutamente verdadeiro de um índio de meio expediente','Sherman Alexie','Romace'),
	('OTOLINA E A GATA AMARELA','Chris Riddell','Ficção'),
	('A Revolta das coisas','Charles Kiefer','Romace'),
	('Zé Perri','Claudio Fragata','Sci-Fi'),
	('Bárbara Debaixo da Chuva','Nilma Lacerda','Fantasia'),
	('Do Jeito Que Eu Gosto','Cecily von Ziegesar','Fantasia'),
	('A Rainha da Fofoca','Meg Cabot','Ficção'),
	('Pão-de-Mel','Rachel Cohn','Aventura'),
	('Siri','Rachel Cohn','Mistério'),
	('Princesa Mia','Meg Cabot','Mistério'),
	('Não Me Esqueça','Cecily von Ziegesar','Mistério'),
	('Rosa & Túmulo','Diana Peterfreund','Sci-Fi'),
	('A Pedra Esculpida','Guillaume Prévost','Suspense'),
	('Sr. Ardiloso Cortês','Derek Landy','Não Ficção'),
	('Garota Perfeita','Mary Hogan','Fantasia'),
	('Artemis Fowl','Eoin Colfer','Ficção'),
	('Garota Sem Limite','Cecily von Ziegesar','Fantasia'),
	('Duplo Fio','Malorie Blackman','Fantasia'),
	('Férias e Encantos','Sarah Mlynowski','Fantasia'),
	('Gregor, O Guerreiro da Superfície','Suzanne Collins','Suspense'),
	('Além do Vale dos Espinhos','Patrick Carman','Fantasia'),
	('A Revanche','Andy McNab','Fantasia'),
	('Cida, a gata maravilha','LUIZ PAULO FACCIOLI','Ficção'),
	('Segredos da Minha Vida em Hollywood: na locação','Jen Calonita','Romace'),
	('Você é um Homem Mau, Sr Gum!','Andy Stanton','Mistério'),
	('Vale dos Dragões','Salamanda Drake','Fantasia'),
	('Eu Não Mentiria Para Você','Cecily von Ziegesar','Romace'),
	('O Soldado','Andy Mcnab','Aventura'),
	('Gossip Girl : Eu Não Mentiria Pra Você','Ziegesar','Romace'),
	('O Livro Perigoso para Garotos','Conn Iggulden','Não Ficção'),
	('Crepúsculo','Meg Cabot','Mistério'),
	('Kiki Strike e a Cidade das Sombras','Kirsten Miller','Romace'),
	('Confissões de uma Banda','Nina Malkin','Suspense'),
	('Nunca Mais!','Cecily von Ziegesar','Aventura'),
	('Vai Sonhando','Cecily von Ziegesar','Não Ficção'),
	('Sapos & Beijos','Sarah Mlynowski','Mistério'),
	('O Selo Médici','Theresa Breslin','Suspense'),
	('Jogo da Velha','Malorie Blackman','Mistério'),
	('A Décima Cidade','Patrick Carman','Sci-Fi'),
	('A Morte é Contagiosa','Charlie Higson','Romace'),
	('Épico','Conor Kostick','Romace'),
	('Um Verão Para Toda Vida','Michael Noonan','Mistério'),
	('Maré de Terror','Justin Somper','Sci-Fi'),
	('A Hora Mais Sombria','Meg Cabot','Mistério'),
	('O Diário da Princesa','Meg Cabot','Ficção'),
	('A princesa à espera','Meg Cabot','Aventura'),
	('A princesa em treinamento','Meg Cabot','Suspense'),
	('Assombrado','Meg Cabot','Ficção'),
	('Feitiços e Sutiãs','Sarah Mlynowski','Sci-Fi'),
	('O Arcano Nove','Meg Cabot','Romace'),
	('A Hora Mais Sombria','Meg Cabot','Suspense'),
	('Minha vizinha Alice','Judi Curtin','Suspense'),
	('A Terra das Sombras','Meg Cabot','Sci-Fi'),
	('Garoto Encontra Garota (Boy Meets Girl)','Meg Cabot','Ficção'),
	('Robinson Crusoe','Daniel Defoe','Aventura'),
	('No Limiar das Colinas Sombrias','Patrick Carman','Fantasia'),
	('Assombrado','Meg Cabot','Fantasia'),
	('A Princesa Sobre os Refletores -Vol. 2','Meg Cabout','Fantasia'),
	('O Arcano Nove','Meg Cabot','Não Ficção'),
	('A Hora Mais Sombria','Meg Cabot','Sci-Fi'),
	('A Terra das Sombras','Meg Cabot','Não Ficção'),
	('Reunião','Meg Cabot','Fantasia'),
	('Paper Money','Adam Smith','Não Ficção'),
	('O vampiro não está tão a fim de você','Vlad Mezrich','Suspense'),
	(' Classic','Galera Record','Suspense'),
	('A Última Palavra','Tamara Ireland Stone','Ficção'),
	('A Ilha do Guardião da Tempestade','Catherine Doyle','Aventura'),
	('O Desgosto de August','Brittany Cavallaro','Sci-Fi');
INSERT INTO livro_livros (titulo, autor, genero) VALUES ('Morte No Verão','Benjamin Black','Sci-Fi'),
	('Aqui, Agora, Sempre','Catherine Isaac','Aventura'),
	('Dora e a Amiga de Verdade','Abby Hanlon','Mistério'),
	('Dois Beijos Para Maddy','Matthew Logelin','Ficção'),
	('A Odisseia de Penélope','Margaret Atwood','Fantasia'),
	('O Mago','Inbali Iserles','Ficção'),
	('Para não esquecer','Clarice Lispector','Mistério'),
	('Felicidade clandestina','Clarice Lispector','Aventura'),
	('Entrevista com Vampiro','Anne Rice','Ficção'),
	('Você é Fodona!','Jen Sincero','Não Ficção'),
	('Confusões de Um Ano Desastroso','Emma Chastain','Sci-Fi'),
	('Modern Love','Daniel Jones','Aventura'),
	('Harry Potter e o Cálice de Fogo','J.K. Rowling','Ficção'),
	('Harry Potter e a Ordem da Fênix','J.K. Rowling','Ficção'),
	('Harry Potter e o Enigma do Príncipe','J.K. Rowling','Romace'),
	('Harry Potter e as Relíquias da Morte','J.K. Rowling','Não Ficção'),
	('Harry Potter e o Prisioneiro de Azkaban','J.K. Rowling','Sci-Fi'),
	('Harry Potter e a Câmara Secreta','J.K. Rowling','Suspense'),
	('Harry Potter e a Pedra Filosofal','J.K. Rowling','Aventura'),
	('A Bela e A Fera','Clarice Lispector','Aventura');

