# Generated by Django 5.0.4 on 2024-04-29 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
        ('usuarios', '0002_usuario_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resenhas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resenha', models.TextField()),
                ('nota', models.IntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('livro_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livro.livros')),
                ('usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'resenha',
            },
        ),
    ]
