# Generated by Django 5.0.4 on 2024-04-10 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("livro", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="livros",
            options={"verbose_name": "livro"},
        ),
    ]
